-- Copyright (c) 2025 Silver Blueprints LLC
-- SPDX-License-Identifier: MIT

-- Application user, authenticated via passkeys (WebAuthn) - see
-- webauthn_credential below. email is the human-facing identifier used for
-- account lookup/display and as the WebAuthn "user.name" during passkey
-- registration; the actual credential material lives in
-- webauthn_credential, never here.
CREATE TABLE public.app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    display_name VARCHAR(200),
    -- System-wide, not business-scoped (unlike business_user.role): can create a business
    -- (see auth.RequireGlobalAdmin, BusinessService.CreateBusiness) and invite/manage users on
    -- any business, full stop - nobody else can do either. The very first global admin has no
    -- existing admin to grant it, so it's bootstrapped from DENARIX_BOOTSTRAP_ADMIN_EMAIL at server
    -- startup instead (internal/auth/bootstrap.go); every subsequent one is promoted via
    -- UserService.SetGlobalAdmin, which itself requires an existing global admin to call.
    is_global_admin BOOLEAN DEFAULT FALSE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX app_user_email_uindex ON public.app_user(email);
-- Enforces "only one global admin" at the DB level as a hard backstop, not just application
-- logic: indexing a constant expression with a partial WHERE clause means at most one row can
-- ever satisfy is_global_admin = TRUE. auth.SetGlobalAdmin transfers admin status (clears the
-- old holder, sets the new one, in one transaction) precisely so it never even attempts to
-- violate this.
CREATE UNIQUE INDEX app_user_single_global_admin_uindex ON public.app_user ((1)) WHERE is_global_admin = TRUE AND deleted_at IS NULL;

-- One row per registered passkey (a user may register more than one - e.g.
-- a MacBook and an iPhone). credential_id/public_key are the raw WebAuthn
-- values as produced by a relying-party library (e.g. go-webauthn/webauthn);
-- sign_count supports its clone-detection check. transports is a
-- comma-separated hint list (usb, nfc, ble, internal, hybrid) rather than
-- an array type, consistent with the rest of the schema avoiding
-- Postgres-specific array/enum types.
CREATE TABLE public.webauthn_credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.app_user(id),
    credential_id BYTEA NOT NULL,
    public_key BYTEA NOT NULL,
    attestation_type VARCHAR(50),
    transports VARCHAR(100),
    aaguid BYTEA,
    sign_count BIGINT DEFAULT 0 NOT NULL,
    -- BE ("this credential is capable of being backed up/synced - e.g. via iCloud Keychain -
    -- and should NEVER change") and BS ("it currently *is* backed up/synced - can change").
    -- go-webauthn's FinishPasskeyLogin refuses a login if the ceremony's BE flag doesn't match
    -- what's on file here, so both must be persisted from the registration ceremony - not
    -- storing them at all made this table's BE always false, so every login against a real
    -- backup-eligible authenticator (any Apple platform passkey) failed with "Backup Eligible
    -- flag inconsistency detected during login validation".
    backup_eligible BOOLEAN DEFAULT FALSE NOT NULL,
    backup_state BOOLEAN DEFAULT FALSE NOT NULL,
    name VARCHAR(200),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    last_used_at TIMESTAMP
);

CREATE UNIQUE INDEX webauthn_credential_credential_id_uindex ON public.webauthn_credential(credential_id);
CREATE INDEX webauthn_credential_user_id_idx ON public.webauthn_credential(user_id);

-- credential_enrollment is a single-use, admin-issued (or bootstrap-issued) token that
-- authorizes enrolling a NEW passkey onto an EXISTING app_user. It is the ONLY way to add a
-- credential to an account that already has one: passkey registration derives its identity
-- entirely from the token it is handed (a business_invite for a brand-new account, or one of
-- these for an existing one), never from a free-typed email, so knowing someone's email is not
-- enough to enroll a device against their account. See internal/auth/webauthn.go.
--
--   * purpose RESET     - issued by a global admin or a business OWNER/ADMIN via
--                         UserService.ResetUserCredentials (a lost/replaced device).
--   * purpose BOOTSTRAP - minted for the first global admin at server startup, since they have
--                         no inviter above them (see internal/auth/bootstrap.go).
--
-- revoke_existing (default true, the "reset" semantics) deletes the user's other passkeys when
-- this token is redeemed, so a lost device can't still sign in; false just adds a device.
-- Revocation happens at REDEMPTION, not when the token is minted, so minting one is
-- non-destructive (a break-glass restart that re-mints does not wipe a working credential).
CREATE TABLE public.credential_enrollment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.app_user(id),
    token_hash VARCHAR(64) NOT NULL,
    revoke_existing BOOLEAN NOT NULL DEFAULT TRUE,
    purpose VARCHAR(20) NOT NULL DEFAULT 'RESET' CHECK (purpose IN ('RESET', 'BOOTSTRAP')),
    created_by_user_id BIGINT REFERENCES public.app_user(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    consumed_at TIMESTAMP
);

CREATE UNIQUE INDEX credential_enrollment_token_hash_uindex ON public.credential_enrollment(token_hash);
CREATE INDEX credential_enrollment_user_id_idx ON public.credential_enrollment(user_id);
-- At most one live (unconsumed, unexpired-by-intent) enrollment per user at a time keeps a
-- break-glass restart loop from piling up tokens; expiry is enforced in the query, not here.
CREATE UNIQUE INDEX credential_enrollment_user_pending_uindex
    ON public.credential_enrollment(user_id) WHERE consumed_at IS NULL;

-- Optimistic concurrency, Kubernetes-style: every row on a table that has this trigger
-- carries a resource_version that this bumps on every UPDATE - any UPDATE, including
-- soft-deletes, status flips, and internal side effects like ConsumeNextInvoiceNumber or
-- ApplyPaymentToInvoice - so it strictly increases with each committed write to the row,
-- and can't be set from the outside (NEW.resource_version is overwritten unconditionally).
-- The API returns it on every read and accepts it back as an optional precondition on every
-- Update*/Deactivate* RPC (`WHERE resource_version = $expected`): a caller holding a stale
-- copy gets ABORTED instead of silently overwriting whoever wrote in between. Unset (0) means
-- unconditional, same as an empty resourceVersion in k8s. See docs/schema.md, "Patterns".
CREATE FUNCTION public.bump_resource_version() RETURNS TRIGGER AS $$
BEGIN
    NEW.resource_version := OLD.resource_version + 1;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TABLE public.business (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    tax_id VARCHAR(50),
    address_line1 VARCHAR(255),
    address_line2 VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(50),
    postal_code VARCHAR(20),
    country VARCHAR(2) DEFAULT 'US',
    phone VARCHAR(50),
    email VARCHAR(255),
    website_url VARCHAR(500),
    logo_url VARCHAR(500),
    default_payment_terms_days INTEGER DEFAULT 30,
    default_tax_rate DECIMAL(5,4) DEFAULT 0.00,
    default_invoice_terms TEXT,
    default_estimate_terms TEXT,
    invoice_number_prefix VARCHAR(10) DEFAULT 'INV',
    estimate_number_prefix VARCHAR(10) DEFAULT 'EST',
    next_invoice_number INTEGER DEFAULT 1000,
    next_estimate_number INTEGER DEFAULT 1000,
    timezone VARCHAR(50) DEFAULT 'America/New_York',
    currency_code VARCHAR(3) DEFAULT 'USD',
    -- This business's own system ledger_account rows (see
    -- internal/server/system_accounts.go, internal/periodclose/provision.go) - set once,
    -- the first time each is provisioned or self-healed, never re-derived by lookup
    -- afterward. FK added below, after ledger_account exists (ledger_account.business_id
    -- already references this table, so the constraint can't be inline here without a
    -- forward reference).
    ar_account_id INTEGER,
    ap_account_id INTEGER,
    income_summary_account_id INTEGER,
    retained_earnings_account_id INTEGER,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_by_user_id BIGINT REFERENCES public.app_user(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    resource_version BIGINT DEFAULT 1 NOT NULL,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX business_name_uindex
    on public.business(name);
CREATE INDEX business_created_by_user_id_idx ON public.business(created_by_user_id);

CREATE TRIGGER business_resource_version
    BEFORE UPDATE ON public.business
    FOR EACH ROW EXECUTE FUNCTION public.bump_resource_version();

-- Membership: which app_user can access which business, and at what role. A
-- user can belong to multiple businesses; a business can have multiple
-- users. Role as VARCHAR + CHECK matches the schema's existing string-enum
-- convention (invoice.status, payment.payment_type, ...) rather than a
-- native Postgres enum type.
CREATE TABLE public.business_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    user_id BIGINT NOT NULL REFERENCES public.app_user(id),
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER' CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER')),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE UNIQUE INDEX business_user_business_user_uindex ON public.business_user(business_id, user_id);
CREATE INDEX business_user_user_id_idx ON public.business_user(user_id);

-- A pending grant of business access to an email that hasn't necessarily registered a passkey
-- yet (see AcceptBusinessInvite) - not a business_user row itself, which is only created once
-- accepted. token_hash follows the exact same pattern as user_session.refresh_token_hash: a
-- sha256 digest, never the raw token, which is shown to the inviter exactly once
-- (CreateBusinessInviteResponse) and shared with the invitee out-of-band (Slack, text, email -
-- denarix never sends it itself). Requiring the token (not just knowing the invited email) is what
-- stops anyone who merely guesses/knows an email from claiming access - passkey registration
-- itself has no email-ownership verification (see internal/auth/webauthn.go).
CREATE TABLE public.business_invite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    email VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'MEMBER' CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER')),
    token_hash VARCHAR(64) NOT NULL,
    invited_by_user_id BIGINT REFERENCES public.app_user(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    accepted_at TIMESTAMP,
    accepted_by_user_id BIGINT REFERENCES public.app_user(id),
    revoked_at TIMESTAMP
);

CREATE UNIQUE INDEX business_invite_token_hash_uindex ON public.business_invite(token_hash);
CREATE INDEX business_invite_business_id_idx ON public.business_invite(business_id);
-- Only one outstanding (not yet accepted or revoked) invite per business+email at a time -
-- re-inviting the same address means revoking the old one first, so there's never ambiguity
-- about which token is actually live.
CREATE UNIQUE INDEX business_invite_business_email_pending_uindex
    ON public.business_invite(business_id, lower(email)) WHERE accepted_at IS NULL AND revoked_at IS NULL;

-- Server-side refresh-token storage for dxctl/API sessions. Short-lived
-- signed access tokens (JWT) are verified in-process on every gRPC call with
-- no DB hit; only the long-lived refresh token here is server-side and
-- revocable. refresh_token_hash stores a sha256 digest - the raw token is
-- never persisted.
CREATE TABLE public.user_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.app_user(id),
    refresh_token_hash VARCHAR(64) NOT NULL,
    client_name VARCHAR(200),
    issued_at TIMESTAMP DEFAULT NOW() NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    last_used_at TIMESTAMP,
    revoked_at TIMESTAMP,
    replaced_by_session_id BIGINT REFERENCES public.user_session(id)
);

CREATE UNIQUE INDEX user_session_refresh_token_hash_uindex ON public.user_session(refresh_token_hash);
CREATE INDEX user_session_user_id_idx ON public.user_session(user_id);

CREATE TABLE public.ledger_account_type (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    normal_balance VARCHAR(10) NOT NULL CHECK (normal_balance IN ('DEBIT', 'CREDIT')),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

-- Which side of the balance sheet equation an account sits on
-- (asset/liability/equity/revenue/expense) is already derivable from
-- ledger_account_type + normal_balance above, so no separate table is
-- needed for that. Cash-flow classification (Operating/Investing/
-- Financing) is not derivable from account_type, hence this dedicated table.
CREATE TABLE public.cash_flow_category (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    display_sequence INTEGER DEFAULT 0 NOT NULL
);

-- Presentation-only grouping for the balance sheet report: which section an
-- account is shown under (Long-term Assets, Current Assets & Liabilities,
-- Long-term Liabilities, Capital & Reserves). Distinct from
-- ledger_account_type: type drives debit/credit accounting behavior and
-- which side of the equation an account is on, but nothing about
-- account_type says whether an ASSETS account is a current or long-term
-- one - that's business judgment (a laptop vs. a bank account are both
-- ASSETS), hence this separate table.
CREATE TABLE public.balance_sheet_category (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    display_sequence INTEGER DEFAULT 0 NOT NULL
);

-- Presentation-only grouping for the income statement report: which section an EXPENSES/REVENUE
-- account is shown under (Revenue, Cost of Goods Sold, Operating Expenses). Splitting EXPENSES
-- into Cost of Goods Sold vs Operating Expenses is what makes Gross Profit (Revenue - COGS) -
-- the standard first subtotal on a US income statement - computable. Identified by row (id/name),
-- same as balance_sheet_category, rather than a boolean flag on ledger_account.
CREATE TABLE public.income_statement_category (
    id INTEGER PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    display_sequence INTEGER DEFAULT 0 NOT NULL
);

-- id is a real identity column (not just INTEGER PRIMARY KEY) so the API can
-- insert new accounts - e.g. period-close's Income Summary/Retained Earnings
-- provisioning - without hand-rolling ID allocation.
CREATE TABLE public.ledger_account (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    account_type_id INTEGER NOT NULL REFERENCES public.ledger_account_type(id),
    code VARCHAR(20) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    parent_account_id INTEGER REFERENCES public.ledger_account(id),
    is_system BOOLEAN DEFAULT FALSE NOT NULL,
    is_reconcilable BOOLEAN DEFAULT FALSE NOT NULL,
    is_container BOOLEAN DEFAULT FALSE NOT NULL,
    display_sequence INTEGER DEFAULT 0 NOT NULL,
    cash_flow_category_id INTEGER REFERENCES public.cash_flow_category(id),
    balance_sheet_category_id INTEGER REFERENCES public.balance_sheet_category(id),
    income_statement_category_id INTEGER REFERENCES public.income_statement_category(id),
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_by_user_id BIGINT REFERENCES public.app_user(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    resource_version BIGINT DEFAULT 1 NOT NULL
);

CREATE UNIQUE INDEX ledger_account_business_code_uindex
    ON public.ledger_account(business_id, code);
CREATE INDEX ledger_account_created_by_user_id_idx ON public.ledger_account(created_by_user_id);
CREATE INDEX ledger_account_balance_sheet_category_id_idx ON public.ledger_account(balance_sheet_category_id);
CREATE INDEX ledger_account_income_statement_category_id_idx ON public.ledger_account(income_statement_category_id);
-- Opening balances are not a column here: model them as a ledger_transaction/ledger_entry
-- pair against a system "Opening Balance Equity" account (is_system = true) instead,
-- keeping the ledger strictly double-entry with no special-cased balance field.
-- Running balances are likewise not cached on this table; compute by aggregating
-- ledger_entry per account, and revisit only if query performance demands a cache.
-- Excludes is_system rows: those are uniquely identified by code already (which embeds the
-- owning contact's id for a customer/vendor sub-account - see
-- internal/server/system_accounts.go), and their name mirrors the contact's own display name,
-- which is legitimately allowed to collide (two different customers can both be "John Smith").
CREATE UNIQUE INDEX ledger_account_business_parent_name_uindex
    ON public.ledger_account(business_id, COALESCE(parent_account_id, 0), name)
    WHERE NOT is_system;

CREATE TRIGGER ledger_account_resource_version
    BEFORE UPDATE ON public.ledger_account
    FOR EACH ROW EXECUTE FUNCTION public.bump_resource_version();

-- business.*_account_id can only reference ledger_account once it exists - see the columns'
-- own comment on business, above.
ALTER TABLE public.business
    ADD CONSTRAINT business_ar_account_id_fkey FOREIGN KEY (ar_account_id) REFERENCES public.ledger_account(id),
    ADD CONSTRAINT business_ap_account_id_fkey FOREIGN KEY (ap_account_id) REFERENCES public.ledger_account(id),
    ADD CONSTRAINT business_income_summary_account_id_fkey FOREIGN KEY (income_summary_account_id) REFERENCES public.ledger_account(id),
    ADD CONSTRAINT business_retained_earnings_account_id_fkey FOREIGN KEY (retained_earnings_account_id) REFERENCES public.ledger_account(id);

CREATE TABLE public.ledger_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    transaction_date DATE NOT NULL,
    description TEXT,
    reference_number VARCHAR(100),
    -- Set on a reversing transaction (ledgerpost.ReverseTransaction) to the transaction it
    -- mirrors. Unique so a transaction can be reversed at most once, and a reversal is
    -- recognisable as such (and itself refused as a reverse target).
    reverses_ledger_transaction_id BIGINT REFERENCES public.ledger_transaction(id),
    created_by_user_id BIGINT REFERENCES public.app_user(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE INDEX ledger_transaction_business_id_idx ON public.ledger_transaction(business_id);
CREATE INDEX ledger_transaction_date_idx ON public.ledger_transaction(transaction_date);
CREATE INDEX ledger_transaction_created_by_user_id_idx ON public.ledger_transaction(created_by_user_id);
-- Supports ListLedgerTransactions' (transaction_date, id) DESC keyset pagination.
CREATE INDEX ledger_transaction_business_id_date_id_idx
    ON public.ledger_transaction(business_id, transaction_date DESC, id DESC);
CREATE UNIQUE INDEX ledger_transaction_reverses_uindex ON public.ledger_transaction(reverses_ledger_transaction_id)
    WHERE reverses_ledger_transaction_id IS NOT NULL;

CREATE TABLE public.ledger_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    ledger_transaction_id BIGINT NOT NULL REFERENCES public.ledger_transaction(id),
    account_id INTEGER NOT NULL REFERENCES public.ledger_account(id),
    debit_amount DECIMAL(15,2) DEFAULT 0.00 NOT NULL CHECK (debit_amount >= 0),
    credit_amount DECIMAL(15,2) DEFAULT 0.00 NOT NULL CHECK (credit_amount >= 0),
    description TEXT,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP,
    CONSTRAINT ledger_entry_debit_or_credit CHECK (
        (debit_amount > 0 AND credit_amount = 0) OR
        (credit_amount > 0 AND debit_amount = 0)
    )
);

CREATE INDEX ledger_entry_business_id_idx ON public.ledger_entry(business_id);
CREATE INDEX ledger_entry_ledger_transaction_id_idx ON public.ledger_entry(ledger_transaction_id);
CREATE INDEX ledger_entry_account_id_idx ON public.ledger_entry(account_id);

-- End-of-period close: sweeps REVENUE/EXPENSE balances into equity for a closed period, then
-- hard-locks that period so nothing can post or be edited on or before its end date. Two-stage:
-- each REVENUE/EXPENSE account zeroes into a business's Income Summary account, then Income
-- Summary itself zeroes into Retained Earnings - both are ordinary is_system ledger_account rows
-- (EQUITY type) provisioned per business, not special-cased tables, so every closing posting is
-- an ordinary ledger_transaction/ledger_entry pair like any other.
CREATE TABLE public.period_close (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    income_summary_account_id INTEGER NOT NULL REFERENCES public.ledger_account(id),
    retained_earnings_account_id INTEGER NOT NULL REFERENCES public.ledger_account(id),
    closed_at TIMESTAMP DEFAULT NOW() NOT NULL,
    reversed_at TIMESTAMP,
    created_by_user_id BIGINT REFERENCES public.app_user(id),
    CHECK (period_start <= period_end)
);

-- Partial unique index (not just business_id+period_end) so a reversed close's period_end can be
-- reused by a later re-close, while still blocking two simultaneously-active closes on one date.
CREATE UNIQUE INDEX period_close_business_period_end_uindex
    ON public.period_close(business_id, period_end) WHERE reversed_at IS NULL;
CREATE INDEX period_close_business_id_idx ON public.period_close(business_id);
CREATE INDEX period_close_created_by_user_id_idx ON public.period_close(created_by_user_id);

-- Links each ledger_transaction a close generates back to the account it zeroed out, so a
-- close's postings can be located or reversed without pattern-matching on description text.
CREATE TABLE public.period_close_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    period_close_id BIGINT NOT NULL REFERENCES public.period_close(id),
    ledger_transaction_id BIGINT NOT NULL REFERENCES public.ledger_transaction(id),
    source_account_id INTEGER NOT NULL REFERENCES public.ledger_account(id)
);

CREATE INDEX period_close_entry_period_close_id_idx ON public.period_close_entry(period_close_id);
CREATE INDEX period_close_entry_ledger_transaction_id_idx ON public.period_close_entry(ledger_transaction_id);

-- Hard lock: a business closed through period_close.period_end rejects any
-- ledger_transaction/ledger_entry dated on or before that date. Reads only already-committed
-- period_close rows, so a close's own entries - inserted before its period_close row exists -
-- are never blocked by the close they belong to.
CREATE FUNCTION public.enforce_period_lock() RETURNS TRIGGER AS $$
DECLARE
    v_business_id BIGINT;
    v_txn_date DATE;
    v_locked_through DATE;
BEGIN
    IF TG_TABLE_NAME = 'ledger_transaction' THEN
        v_business_id := NEW.business_id;
        v_txn_date := NEW.transaction_date;
    ELSE
        SELECT business_id, transaction_date INTO v_business_id, v_txn_date
        FROM public.ledger_transaction WHERE id = NEW.ledger_transaction_id;
    END IF;

    SELECT MAX(period_end) INTO v_locked_through
    FROM public.period_close
    WHERE business_id = v_business_id AND reversed_at IS NULL;

    IF v_locked_through IS NOT NULL AND v_txn_date <= v_locked_through THEN
        RAISE EXCEPTION 'business % is closed through %, cannot post or modify a transaction dated %',
            v_business_id, v_locked_through, v_txn_date;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ledger_transaction_period_lock
    BEFORE INSERT OR UPDATE OF transaction_date, business_id ON public.ledger_transaction
    FOR EACH ROW EXECUTE FUNCTION public.enforce_period_lock();

CREATE TRIGGER ledger_entry_period_lock
    BEFORE INSERT OR UPDATE OF debit_amount, credit_amount, account_id, deleted_at ON public.ledger_entry
    FOR EACH ROW EXECUTE FUNCTION public.enforce_period_lock();

CREATE TABLE public.bank_statement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    ledger_account_id INTEGER NOT NULL REFERENCES public.ledger_account(id),
    statement_name VARCHAR(200) NOT NULL,
    statement_date DATE NOT NULL,
    opening_balance DECIMAL(15,2),
    closing_balance DECIMAL(15,2),
    created_by_user_id BIGINT REFERENCES public.app_user(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP,
    resource_version BIGINT DEFAULT 1 NOT NULL
);

CREATE INDEX bank_statement_business_id_idx ON public.bank_statement(business_id);
CREATE INDEX bank_statement_ledger_account_id_idx ON public.bank_statement(ledger_account_id);
CREATE INDEX bank_statement_date_idx ON public.bank_statement(statement_date);
CREATE INDEX bank_statement_created_by_user_id_idx ON public.bank_statement(created_by_user_id);

CREATE TRIGGER bank_statement_resource_version
    BEFORE UPDATE ON public.bank_statement
    FOR EACH ROW EXECUTE FUNCTION public.bump_resource_version();

CREATE TABLE public.bank_statement_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_statement_id BIGINT NOT NULL REFERENCES public.bank_statement(id),
    ledger_transaction_id BIGINT NOT NULL REFERENCES public.ledger_transaction(id),
    display_sequence INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE UNIQUE INDEX bank_statement_line_statement_transaction_uindex
    ON public.bank_statement_line(bank_statement_id, ledger_transaction_id);
CREATE INDEX bank_statement_line_ledger_transaction_id_idx ON public.bank_statement_line(ledger_transaction_id);

CREATE TABLE public.tax_rate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    name VARCHAR(100) NOT NULL,
    rate DECIMAL(5,4) NOT NULL,
    tax_liability_account_id INTEGER NOT NULL REFERENCES public.ledger_account(id),
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_by_user_id BIGINT REFERENCES public.app_user(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    resource_version BIGINT DEFAULT 1 NOT NULL
);

CREATE UNIQUE INDEX tax_rate_business_name_uindex ON public.tax_rate(business_id, name);
CREATE INDEX tax_rate_tax_liability_account_id_idx ON public.tax_rate(tax_liability_account_id);
CREATE INDEX tax_rate_created_by_user_id_idx ON public.tax_rate(created_by_user_id);

CREATE TRIGGER tax_rate_resource_version
    BEFORE UPDATE ON public.tax_rate
    FOR EACH ROW EXECUTE FUNCTION public.bump_resource_version();

CREATE INDEX ledger_account_cash_flow_category_id_idx ON public.ledger_account(cash_flow_category_id);

-- Generic party record, reusable for both accounts receivable (customers) and
-- accounts payable (vendors) - a party can be either or both. Which role(s) a
-- contact plays, and that role's own AR/AP sub-ledger account, live in the
-- customer/vendor tables below (row existence is the flag, not a boolean),
-- not on contact itself.
-- estimate.customer_id still keeps its AR-specific name (estimates are
-- inherently a sales-side document, see the estimate table below). invoice
-- and payment generalized to contact_id since both can now represent either
-- AR or AP activity (see invoice.invoice_type / payment.payment_type).
CREATE TABLE public.contact (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    contact_number VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(255),
    phone VARCHAR(50),
    billing_address_line1 VARCHAR(255),
    billing_address_line2 VARCHAR(255),
    billing_city VARCHAR(100),
    billing_state VARCHAR(50),
    billing_postal_code VARCHAR(20),
    billing_country VARCHAR(2) DEFAULT 'US',
    shipping_address_line1 VARCHAR(255),
    shipping_address_line2 VARCHAR(255),
    shipping_city VARCHAR(100),
    shipping_state VARCHAR(50),
    shipping_postal_code VARCHAR(20),
    shipping_country VARCHAR(2) DEFAULT 'US',
    payment_terms_days INTEGER DEFAULT 30,
    credit_limit DECIMAL(15,2),
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_by_user_id BIGINT REFERENCES public.app_user(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    resource_version BIGINT DEFAULT 1 NOT NULL,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX contact_business_number_uindex
    ON public.contact(business_id, contact_number);
CREATE INDEX contact_created_by_user_id_idx ON public.contact(created_by_user_id);

CREATE TRIGGER contact_resource_version
    BEFORE UPDATE ON public.contact
    FOR EACH ROW EXECUTE FUNCTION public.bump_resource_version();

-- A contact plays the customer role when it has a row here. ledger_account_id
-- is that customer's own AR sub-ledger account (see ledger_account.parent_account_id/
-- is_container - a business rolls its customer accounts up under a single "Accounts
-- Receivable" container account for balance sheet reporting, rather than showing
-- every customer as its own top-level line).
CREATE TABLE public.customer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL REFERENCES public.contact(id),
    ledger_account_id INTEGER REFERENCES public.ledger_account(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE UNIQUE INDEX customer_contact_id_uindex ON public.customer(contact_id);
CREATE INDEX customer_ledger_account_id_idx ON public.customer(ledger_account_id);

-- Same pattern as customer, for the vendor (AP) role - ledger_account_id is that
-- vendor's own AP sub-ledger account, rolled up under "Accounts Payable".
CREATE TABLE public.vendor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT NOT NULL REFERENCES public.contact(id),
    ledger_account_id INTEGER REFERENCES public.ledger_account(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE UNIQUE INDEX vendor_contact_id_uindex ON public.vendor(contact_id);
CREATE INDEX vendor_ledger_account_id_idx ON public.vendor(ledger_account_id);

-- item is the sales/purchase catalog: anything that can appear as a line on an
-- estimate or invoice. item_type says how the business treats it -
--   SERVICE       : labour/time, nothing physical (the original "service" row)
--   NON_INVENTORY : a physical product that is sold/bought but whose stock is
--                   not tracked (drop-shipped, consumables, one-offs)
--   INVENTORY     : a physical product whose on-hand quantity the business
--                   wants tracked
-- Only the classification exists so far - INVENTORY carries no quantity,
-- asset account or COGS behaviour yet; that lands alongside stock movements.
-- More modes are expected, hence VARCHAR + CHECK like the schema's other
-- string enums rather than a boolean pair.
CREATE TABLE public.item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    item_code VARCHAR(50) NOT NULL,
    item_type VARCHAR(20) NOT NULL DEFAULT 'SERVICE' CHECK (item_type IN ('SERVICE', 'NON_INVENTORY', 'INVENTORY')),
    name VARCHAR(200) NOT NULL,
    description TEXT,
    unit_of_measure VARCHAR(20) DEFAULT 'EACH',
    cost_price DECIMAL(15,2) DEFAULT 0.00,
    retail_price DECIMAL(15,2) NOT NULL,
    is_taxable BOOLEAN DEFAULT FALSE NOT NULL,
    -- References tax_rate.id - an item is catalog data, not a historical
    -- transaction, so unlike invoice_line_item/estimate_line_item there's no
    -- need to also snapshot a decimal rate alongside the reference.
    default_tax_rate_id BIGINT REFERENCES public.tax_rate(id),
    -- The revenue/expense ledger_account every invoice line for this item
    -- posts to - unlike default_tax_rate_id above this is *the* account, not
    -- a default: NewInvoiceLineItem has no per-line override and CreateItem
    -- requires it. Nullable only because rows created before that rule may
    -- lack one; such an item is rejected at invoice time
    -- (see docs/schema.md, "item" / "invoice_line_item.ledger_account_id").
    default_ledger_account_id INTEGER REFERENCES public.ledger_account(id),
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_by_user_id BIGINT REFERENCES public.app_user(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    resource_version BIGINT DEFAULT 1 NOT NULL,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX item_business_code_uindex
    ON public.item(business_id, item_code);
CREATE INDEX item_business_active_idx ON public.item(business_id, is_active);
CREATE INDEX item_business_type_idx ON public.item(business_id, item_type);
CREATE INDEX item_default_tax_rate_id_idx ON public.item(default_tax_rate_id);
CREATE INDEX item_default_ledger_account_id_idx ON public.item(default_ledger_account_id);
CREATE INDEX item_created_by_user_id_idx ON public.item(created_by_user_id);

CREATE TRIGGER item_resource_version
    BEFORE UPDATE ON public.item
    FOR EACH ROW EXECUTE FUNCTION public.bump_resource_version();

CREATE TABLE public.estimate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    customer_id BIGINT NOT NULL REFERENCES public.contact(id),
    estimate_number VARCHAR(50) NOT NULL,
    estimate_date DATE NOT NULL,
    expiration_date DATE NOT NULL,
    subtotal DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    total_tax_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(15,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'SENT', 'ACCEPTED', 'DECLINED', 'EXPIRED')),
    notes TEXT,
    terms TEXT,
    created_by_user_id BIGINT REFERENCES public.app_user(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    resource_version BIGINT DEFAULT 1 NOT NULL,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX estimate_business_number_uindex
    ON public.estimate(business_id, estimate_number);
CREATE INDEX estimate_customer_id_idx ON public.estimate(customer_id);
CREATE INDEX estimate_status_idx ON public.estimate(status);
CREATE INDEX estimate_expiration_date_idx ON public.estimate(expiration_date);
CREATE INDEX estimate_created_by_user_id_idx ON public.estimate(created_by_user_id);

CREATE TRIGGER estimate_resource_version
    BEFORE UPDATE ON public.estimate
    FOR EACH ROW EXECUTE FUNCTION public.bump_resource_version();

-- item_id: every line references a catalog item (API-enforced, same rule as
-- invoice_line_item below); nullable only for pre-catalog rows.
CREATE TABLE public.estimate_line_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    estimate_id BIGINT NOT NULL REFERENCES public.estimate(id),
    item_id BIGINT REFERENCES public.item(id),
    line_number INTEGER NOT NULL,
    description TEXT NOT NULL,
    quantity DECIMAL(15,4) NOT NULL DEFAULT 1.0000,
    unit_price DECIMAL(15,2) NOT NULL,
    line_subtotal DECIMAL(15,2) NOT NULL,
    is_taxable BOOLEAN DEFAULT FALSE NOT NULL,
    tax_rate_id BIGINT REFERENCES public.tax_rate(id),
    tax_rate DECIMAL(5,4) DEFAULT 0.00,
    tax_amount DECIMAL(15,2) DEFAULT 0.00 NOT NULL,
    line_total DECIMAL(15,2) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE INDEX estimate_line_item_estimate_id_idx ON public.estimate_line_item(estimate_id);
CREATE INDEX estimate_line_item_item_id_idx ON public.estimate_line_item(item_id);
CREATE INDEX estimate_line_item_tax_rate_id_idx ON public.estimate_line_item(tax_rate_id);

-- invoice_type distinguishes accounts-receivable (SALES: sent to a customer)
-- from accounts-payable (PURCHASE: a vendor bill received) documents, sharing
-- one table/shape rather than splitting into a separate bill/bill_line_item
-- pair - similar to the Odoo account.move/move_type pattern. contact_id references either a
-- customer or vendor contact depending on invoice_type (see
-- contact.is_customer/is_vendor); invoice_number for a PURCHASE row is
-- typically the vendor's own document number, not one we generate.
CREATE TABLE public.invoice (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    contact_id BIGINT NOT NULL REFERENCES public.contact(id),
    invoice_type VARCHAR(20) NOT NULL DEFAULT 'SALES' CHECK (invoice_type IN ('SALES', 'PURCHASE')),
    estimate_id BIGINT REFERENCES public.estimate(id),
    invoice_number VARCHAR(50) NOT NULL,
    invoice_date DATE NOT NULL,
    due_date DATE NOT NULL,
    subtotal DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    total_tax_amount DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(15,2) NOT NULL,
    paid_amount DECIMAL(15,2) DEFAULT 0.00,
    balance_due DECIMAL(15,2) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'SENT', 'PAID', 'OVERDUE', 'CANCELLED')),
    notes TEXT,
    terms TEXT,
    -- Set once the invoice is posted to the ledger (see invoice_line_item's
    -- ledger_account_id below) - links the business document back to the GL
    -- entry it produced. NULL for an unposted (e.g. still-DRAFT, or never
    -- wired to an account) invoice.
    ledger_transaction_id BIGINT REFERENCES public.ledger_transaction(id),
    created_by_user_id BIGINT REFERENCES public.app_user(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    resource_version BIGINT DEFAULT 1 NOT NULL,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX invoice_business_number_uindex
    ON public.invoice(business_id, invoice_number);
CREATE INDEX invoice_contact_id_idx ON public.invoice(contact_id);
CREATE INDEX invoice_estimate_id_idx ON public.invoice(estimate_id);
CREATE INDEX invoice_status_idx ON public.invoice(status);
CREATE INDEX invoice_due_date_idx ON public.invoice(due_date);
CREATE INDEX invoice_type_idx ON public.invoice(invoice_type);
CREATE INDEX invoice_created_by_user_id_idx ON public.invoice(created_by_user_id);
CREATE INDEX invoice_ledger_transaction_id_idx ON public.invoice(ledger_transaction_id);

CREATE TRIGGER invoice_resource_version
    BEFORE UPDATE ON public.invoice
    FOR EACH ROW EXECUTE FUNCTION public.bump_resource_version();

-- item_id: every line references a catalog item (API-enforced - see
-- docs/schema.md, "invoice_line_item.item_id"); nullable only for rows that
-- predate the catalog, which are read-only history.
-- ledger_account_id: which revenue (SALES) or expense (PURCHASE) account
-- this line posts to - always the item's default_ledger_account_id,
-- snapshotted here at posting time so a later change to the item doesn't
-- rewrite posted invoices. Never caller-supplied. Nullable for the same
-- legacy reason as item_id; every line the API creates has one.
CREATE TABLE public.invoice_line_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES public.invoice(id),
    item_id BIGINT REFERENCES public.item(id),
    ledger_account_id INTEGER REFERENCES public.ledger_account(id),
    line_number INTEGER NOT NULL,
    description TEXT NOT NULL,
    quantity DECIMAL(15,4) NOT NULL DEFAULT 1.0000,
    unit_price DECIMAL(15,2) NOT NULL,
    line_subtotal DECIMAL(15,2) NOT NULL,
    is_taxable BOOLEAN DEFAULT FALSE NOT NULL,
    tax_rate_id BIGINT REFERENCES public.tax_rate(id),
    tax_rate DECIMAL(5,4) DEFAULT 0.00,
    tax_amount DECIMAL(15,2) DEFAULT 0.00 NOT NULL,
    line_total DECIMAL(15,2) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE INDEX invoice_line_item_invoice_id_idx ON public.invoice_line_item(invoice_id);
CREATE INDEX invoice_line_item_item_id_idx ON public.invoice_line_item(item_id);
CREATE INDEX invoice_line_item_tax_rate_id_idx ON public.invoice_line_item(tax_rate_id);
CREATE INDEX invoice_line_item_ledger_account_id_idx ON public.invoice_line_item(ledger_account_id);

-- payment_type carries direction (money received from a customer vs money we
-- paid to a vendor) independent of invoice_id, since invoice_id is nullable
-- (a deposit/retainer/on-account payment may exist with no linked invoice, so
-- direction can't always be inferred by joining through to invoice.invoice_type).
CREATE TABLE public.payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    contact_id BIGINT NOT NULL REFERENCES public.contact(id),
    payment_type VARCHAR(20) NOT NULL DEFAULT 'RECEIVED' CHECK (payment_type IN ('RECEIVED', 'MADE')),
    payment_number VARCHAR(50) NOT NULL,
    payment_date DATE NOT NULL,
    amount DECIMAL(15,2) NOT NULL CHECK (amount > 0),
    payment_method VARCHAR(20) NOT NULL CHECK (payment_method IN ('CASH', 'CHECK', 'CREDIT_CARD', 'ACH', 'WIRE', 'OTHER')),
    reference_number VARCHAR(100),
    notes TEXT,
    -- The cash/bank account this payment hit - the other side of the
    -- contact's AR/AP account (customer/vendor.ledger_account_id) when posted.
    -- NULL means this payment isn't posted to the ledger.
    ledger_account_id INTEGER REFERENCES public.ledger_account(id),
    -- Set once posted - links back to the GL entry this payment produced.
    ledger_transaction_id BIGINT REFERENCES public.ledger_transaction(id),
    created_by_user_id BIGINT REFERENCES public.app_user(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE UNIQUE INDEX payment_business_number_uindex
    ON public.payment(business_id, payment_number);
CREATE INDEX payment_contact_id_idx ON public.payment(contact_id);
CREATE INDEX payment_date_idx ON public.payment(payment_date);
CREATE INDEX payment_type_idx ON public.payment(payment_type);
CREATE INDEX payment_created_by_user_id_idx ON public.payment(created_by_user_id);
CREATE INDEX payment_ledger_account_id_idx ON public.payment(ledger_account_id);
CREATE INDEX payment_ledger_transaction_id_idx ON public.payment(ledger_transaction_id);

-- Join table between payment and invoice: applied_amount is how much of the
-- payment went to that invoice specifically, so one payment (e.g. a single
-- deposit) can apply across several invoices at once rather than the
-- one-payment-one-invoice limit a single nullable payment.invoice_id would
-- impose. The sum across one payment's applications shouldn't exceed its
-- amount - enforced at the application layer, not here.
CREATE TABLE public.payment_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES public.payment(id),
    invoice_id BIGINT NOT NULL REFERENCES public.invoice(id),
    applied_amount DECIMAL(15,2) NOT NULL CHECK (applied_amount > 0),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL
);

CREATE UNIQUE INDEX payment_application_payment_invoice_uindex
    ON public.payment_application(payment_id, invoice_id);
CREATE INDEX payment_application_invoice_id_idx ON public.payment_application(invoice_id);

-- Polymorphic store for AI-generated context (summaries, categorization hints,
-- anomaly flags, user notes) tied to any entity (customer, ledger_transaction,
-- ledger_account, invoice, ...), so a future Claude Code session (via the MCP
-- server) can retrieve prior context about an entity it's working on. No FK on
-- entity_id since it spans multiple target tables. `source`/`metadata` can
-- carry an MCP session/conversation identifier without needing dedicated
-- columns for it.
--
-- Append-only by convention: rows are never edited in place. As granular
-- context accumulates for an entity, a batch of old rows can be rolled up
-- into a single new row (typically context_type = 'summary') with
-- superseded_by_id set on the old rows pointing at it, so retrieval can
-- default to `WHERE superseded_by_id IS NULL` (current context only) while
-- the full trail remains queryable for audit. Genuinely low-value or expired
-- rows are pruned via the existing deleted_at soft-delete; retention policy
-- (what/when to prune) is an application/job concern, not schema.
CREATE TABLE public.entity_context (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,
    context_type VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    metadata JSONB,
    source VARCHAR(100),
    confidence DECIMAL(5,4),
    superseded_by_id BIGINT REFERENCES public.entity_context(id),
    created_by_user_id BIGINT REFERENCES public.app_user(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE INDEX entity_context_entity_idx ON public.entity_context(entity_type, entity_id);
CREATE INDEX entity_context_business_id_idx ON public.entity_context(business_id);
CREATE INDEX entity_context_superseded_by_id_idx ON public.entity_context(superseded_by_id);
CREATE INDEX entity_context_created_by_user_id_idx ON public.entity_context(created_by_user_id);

-- Same polymorphic entity_type/entity_id pattern as entity_context above, for
-- files attached to any entity (receipts, contracts, logos, ...).
-- storage_key is an object key in the internal object-storage backend (SeaweedFS locally -
-- see docker-compose.yml, internal/storage), not a URL - no gRPC caller ever sees it or
-- addresses that backend directly. File bytes are streamed through
-- AttachmentService.UploadAttachment/DownloadAttachment instead
-- (proto/denarix/v1/context.proto), so every read/write is gated by denarix's own auth.
CREATE TABLE public.attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES public.business(id),
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,
    original_filename VARCHAR(500),
    storage_key VARCHAR(1000) NOT NULL,
    content_type VARCHAR(100),
    file_size_bytes BIGINT,
    display_sequence INTEGER DEFAULT 0 NOT NULL,
    created_by_user_id BIGINT REFERENCES public.app_user(id),
    created_at TIMESTAMP DEFAULT NOW() NOT NULL,
    deleted_at TIMESTAMP
);

CREATE INDEX attachment_entity_idx ON public.attachment(entity_type, entity_id);
CREATE INDEX attachment_business_id_idx ON public.attachment(business_id);
CREATE INDEX attachment_created_by_user_id_idx ON public.attachment(created_by_user_id);

INSERT INTO public.ledger_account_type (id, name, description, normal_balance) VALUES
(1, 'ASSETS', 'Economic resources owned by the company', 'DEBIT'),
(2, 'LIABILITIES', 'Debts and obligations owed by the company', 'CREDIT'),
(3, 'EQUITY', 'Ownership interest in the company', 'CREDIT'),
(4, 'REVENUE', 'Income earned from business operations', 'CREDIT'),
(5, 'EXPENSES', 'Costs incurred in business operations', 'DEBIT'),
(6, 'TAX_LIABILITY', 'Taxes collected on behalf of government agencies', 'CREDIT');

INSERT INTO public.cash_flow_category (id, name, display_sequence) VALUES
(1, 'Operating', 1),
(2, 'Investing', 2),
(3, 'Financing', 3);

INSERT INTO public.balance_sheet_category (id, name, display_sequence) VALUES
(1, 'Long-term Assets', 1),
(2, 'Current Assets & Liabilities', 2),
(3, 'Long-term Liabilities', 3),
(4, 'Capital & Reserves', 4),
(5, 'Opening Balances', 5);

INSERT INTO public.income_statement_category (id, name, display_sequence) VALUES
(1, 'Revenue', 1),
(2, 'Cost of Goods Sold', 2),
(3, 'Operating Expenses', 3);

-- Accounts Receivable / Accounts Payable container accounts for business 1 (the only business
-- that exists today) - every customer/vendor ledger_account rolls up under one of these via
-- parent_account_id, rather than showing as its own top-level balance sheet line. System-account
-- ids are kept below 50 by convention (id is GENERATED BY DEFAULT AS IDENTITY, so an explicit
-- value here doesn't collide with the app's own auto-allocated ids, which start at 1 and climb
-- past this range in practice). Guarded (SELECT ... FROM business WHERE id = 1, ON CONFLICT DO
-- NOTHING) so this is a no-op - not a FK violation - on a fresh install with no business rows yet;
-- any other/future business needs its own AR/AP provisioned separately.
--
-- Codes follow a standard QuickBooks-style chart-of-accounts numbering convention: 1000s Assets,
-- 2000s Liabilities, 3000s Equity, 4000s Revenue, 5000s Cost of Goods Sold, 6000s Operating
-- Expenses (see internal/periodclose.IncomeSummaryCode/RetainedEarningsCode for the two other
-- codes this convention constrains, and docs/schema.md for the rest of the live chart).
INSERT INTO public.ledger_account (id, business_id, account_type_id, code, name, is_system, is_container, balance_sheet_category_id, display_sequence)
SELECT 10, b.id, 1, '1100', 'Accounts Receivable', TRUE, TRUE, 2, 0
FROM public.business b WHERE b.id = 1
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.ledger_account (id, business_id, account_type_id, code, name, is_system, is_container, balance_sheet_category_id, display_sequence)
SELECT 11, b.id, 2, '2000', 'Accounts Payable', TRUE, TRUE, 2, 0
FROM public.business b WHERE b.id = 1
ON CONFLICT (id) DO NOTHING;
