// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: banking.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBankStatementLines = `-- name: CountBankStatementLines :one
SELECT COUNT(*) FROM bank_statement_line WHERE bank_statement_id = $1
`

func (q *Queries) CountBankStatementLines(ctx context.Context, bankStatementID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countBankStatementLines, bankStatementID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBankStatement = `-- name: CreateBankStatement :one

INSERT INTO bank_statement (
    business_id, ledger_account_id, statement_name, statement_date,
    opening_balance, closing_balance, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, business_id, ledger_account_id, statement_name, statement_date, opening_balance, closing_balance, created_by_user_id, created_at, updated_at, deleted_at, resource_version
`

type CreateBankStatementParams struct {
	BusinessID      int64          `json:"business_id"`
	LedgerAccountID int32          `json:"ledger_account_id"`
	StatementName   string         `json:"statement_name"`
	StatementDate   pgtype.Date    `json:"statement_date"`
	OpeningBalance  pgtype.Numeric `json:"opening_balance"`
	ClosingBalance  pgtype.Numeric `json:"closing_balance"`
	CreatedByUserID *int64         `json:"created_by_user_id"`
}

// Copyright (c) 2025 Silver Blueprints LLC
// SPDX-License-Identifier: MIT
func (q *Queries) CreateBankStatement(ctx context.Context, arg CreateBankStatementParams) (BankStatement, error) {
	row := q.db.QueryRow(ctx, createBankStatement,
		arg.BusinessID,
		arg.LedgerAccountID,
		arg.StatementName,
		arg.StatementDate,
		arg.OpeningBalance,
		arg.ClosingBalance,
		arg.CreatedByUserID,
	)
	var i BankStatement
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LedgerAccountID,
		&i.StatementName,
		&i.StatementDate,
		&i.OpeningBalance,
		&i.ClosingBalance,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ResourceVersion,
	)
	return i, err
}

const createBankStatementLine = `-- name: CreateBankStatementLine :one
INSERT INTO bank_statement_line (bank_statement_id, ledger_transaction_id, display_sequence)
VALUES ($1, $2, $3)
RETURNING id, bank_statement_id, ledger_transaction_id, display_sequence, created_at
`

type CreateBankStatementLineParams struct {
	BankStatementID     int64 `json:"bank_statement_id"`
	LedgerTransactionID int64 `json:"ledger_transaction_id"`
	DisplaySequence     int32 `json:"display_sequence"`
}

func (q *Queries) CreateBankStatementLine(ctx context.Context, arg CreateBankStatementLineParams) (BankStatementLine, error) {
	row := q.db.QueryRow(ctx, createBankStatementLine, arg.BankStatementID, arg.LedgerTransactionID, arg.DisplaySequence)
	var i BankStatementLine
	err := row.Scan(
		&i.ID,
		&i.BankStatementID,
		&i.LedgerTransactionID,
		&i.DisplaySequence,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateBankStatement = `-- name: DeactivateBankStatement :one
UPDATE bank_statement SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
    AND ($2::bigint IS NULL OR resource_version = $2)
RETURNING id, business_id, ledger_account_id, statement_name, statement_date, opening_balance, closing_balance, created_by_user_id, created_at, updated_at, deleted_at, resource_version
`

type DeactivateBankStatementParams struct {
	ID              int64  `json:"id"`
	ResourceVersion *int64 `json:"resource_version"`
}

func (q *Queries) DeactivateBankStatement(ctx context.Context, arg DeactivateBankStatementParams) (BankStatement, error) {
	row := q.db.QueryRow(ctx, deactivateBankStatement, arg.ID, arg.ResourceVersion)
	var i BankStatement
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LedgerAccountID,
		&i.StatementName,
		&i.StatementDate,
		&i.OpeningBalance,
		&i.ClosingBalance,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ResourceVersion,
	)
	return i, err
}

const deleteBankStatementLine = `-- name: DeleteBankStatementLine :exec
DELETE FROM bank_statement_line
WHERE bank_statement_id = $1 AND ledger_transaction_id = $2
`

type DeleteBankStatementLineParams struct {
	BankStatementID     int64 `json:"bank_statement_id"`
	LedgerTransactionID int64 `json:"ledger_transaction_id"`
}

// Hard delete, not soft: the unique index on (bank_statement_id,
// ledger_transaction_id) would otherwise block re-reconciling the same
// transaction, and a line carries no financial content of its own to keep
// history of.
func (q *Queries) DeleteBankStatementLine(ctx context.Context, arg DeleteBankStatementLineParams) error {
	_, err := q.db.Exec(ctx, deleteBankStatementLine, arg.BankStatementID, arg.LedgerTransactionID)
	return err
}

const getBankStatement = `-- name: GetBankStatement :one
SELECT id, business_id, ledger_account_id, statement_name, statement_date, opening_balance, closing_balance, created_by_user_id, created_at, updated_at, deleted_at, resource_version FROM bank_statement WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBankStatement(ctx context.Context, id int64) (BankStatement, error) {
	row := q.db.QueryRow(ctx, getBankStatement, id)
	var i BankStatement
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LedgerAccountID,
		&i.StatementName,
		&i.StatementDate,
		&i.OpeningBalance,
		&i.ClosingBalance,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ResourceVersion,
	)
	return i, err
}

const getLatestBankStatementForAccount = `-- name: GetLatestBankStatementForAccount :one
SELECT id, business_id, ledger_account_id, statement_name, statement_date, opening_balance, closing_balance, created_by_user_id, created_at, updated_at, deleted_at, resource_version FROM bank_statement
WHERE ledger_account_id = $1
    AND statement_date < $2
    AND id <> $3
    AND deleted_at IS NULL
ORDER BY statement_date DESC, id DESC
LIMIT 1
`

type GetLatestBankStatementForAccountParams struct {
	LedgerAccountID int32       `json:"ledger_account_id"`
	BeforeDate      pgtype.Date `json:"before_date"`
	ExcludeID       int64       `json:"exclude_id"`
}

// Most recent non-deleted statement for an account, strictly before a given
// date - the chaining check in Create/UpdateBankStatement compares its
// opening balance against this one's closing balance. exclude_id keeps an
// update from chaining a statement against itself when its date moves later
// (pass 0 on create).
func (q *Queries) GetLatestBankStatementForAccount(ctx context.Context, arg GetLatestBankStatementForAccountParams) (BankStatement, error) {
	row := q.db.QueryRow(ctx, getLatestBankStatementForAccount, arg.LedgerAccountID, arg.BeforeDate, arg.ExcludeID)
	var i BankStatement
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LedgerAccountID,
		&i.StatementName,
		&i.StatementDate,
		&i.OpeningBalance,
		&i.ClosingBalance,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ResourceVersion,
	)
	return i, err
}

const ledgerEntryExistsForAccount = `-- name: LedgerEntryExistsForAccount :one
SELECT EXISTS(
    SELECT 1 FROM ledger_entry
    WHERE ledger_transaction_id = $1
        AND account_id = $2
        AND deleted_at IS NULL
) AS entry_exists
`

type LedgerEntryExistsForAccountParams struct {
	LedgerTransactionID int64 `json:"ledger_transaction_id"`
	AccountID           int32 `json:"account_id"`
}

func (q *Queries) LedgerEntryExistsForAccount(ctx context.Context, arg LedgerEntryExistsForAccountParams) (bool, error) {
	row := q.db.QueryRow(ctx, ledgerEntryExistsForAccount, arg.LedgerTransactionID, arg.AccountID)
	var entry_exists bool
	err := row.Scan(&entry_exists)
	return entry_exists, err
}

const listBankStatementLines = `-- name: ListBankStatementLines :many
SELECT id, bank_statement_id, ledger_transaction_id, display_sequence, created_at FROM bank_statement_line WHERE bank_statement_id = $1 ORDER BY display_sequence, id
`

func (q *Queries) ListBankStatementLines(ctx context.Context, bankStatementID int64) ([]BankStatementLine, error) {
	rows, err := q.db.Query(ctx, listBankStatementLines, bankStatementID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankStatementLine
	for rows.Next() {
		var i BankStatementLine
		if err := rows.Scan(
			&i.ID,
			&i.BankStatementID,
			&i.LedgerTransactionID,
			&i.DisplaySequence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankStatementLinesByStatementIDs = `-- name: ListBankStatementLinesByStatementIDs :many
SELECT id, bank_statement_id, ledger_transaction_id, display_sequence, created_at FROM bank_statement_line
WHERE bank_statement_id = ANY($1::bigint[])
ORDER BY bank_statement_id, display_sequence, id
`

// Batch form for list handlers.
func (q *Queries) ListBankStatementLinesByStatementIDs(ctx context.Context, bankStatementIds []int64) ([]BankStatementLine, error) {
	rows, err := q.db.Query(ctx, listBankStatementLinesByStatementIDs, bankStatementIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankStatementLine
	for rows.Next() {
		var i BankStatementLine
		if err := rows.Scan(
			&i.ID,
			&i.BankStatementID,
			&i.LedgerTransactionID,
			&i.DisplaySequence,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBankStatements = `-- name: ListBankStatements :many
SELECT id, business_id, ledger_account_id, statement_name, statement_date, opening_balance, closing_balance, created_by_user_id, created_at, updated_at, deleted_at, resource_version FROM bank_statement WHERE business_id = $1 AND deleted_at IS NULL ORDER BY statement_date DESC
`

func (q *Queries) ListBankStatements(ctx context.Context, businessID int64) ([]BankStatement, error) {
	rows, err := q.db.Query(ctx, listBankStatements, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BankStatement
	for rows.Next() {
		var i BankStatement
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.LedgerAccountID,
			&i.StatementName,
			&i.StatementDate,
			&i.OpeningBalance,
			&i.ClosingBalance,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ResourceVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreconciledLedgerTransactions = `-- name: ListUnreconciledLedgerTransactions :many
SELECT DISTINCT lt.id, lt.business_id, lt.transaction_date, lt.description, lt.reference_number, lt.reverses_ledger_transaction_id, lt.created_by_user_id, lt.created_at, lt.updated_at, lt.deleted_at
FROM ledger_transaction lt
JOIN ledger_entry le ON le.ledger_transaction_id = lt.id AND le.deleted_at IS NULL
WHERE le.account_id = $1
    AND lt.deleted_at IS NULL
    AND lt.transaction_date <= $2
    AND NOT EXISTS (
        SELECT 1 FROM bank_statement_line bsl
        JOIN bank_statement bs ON bs.id = bsl.bank_statement_id
        WHERE bsl.ledger_transaction_id = lt.id AND bs.ledger_account_id = $1
            AND bs.deleted_at IS NULL
    )
ORDER BY lt.transaction_date
`

type ListUnreconciledLedgerTransactionsParams struct {
	AccountID   int32       `json:"account_id"`
	ThroughDate pgtype.Date `json:"through_date"`
}

// ledger_transaction rows touching account_id, through_date, that have no
// bank_statement_line yet under any bank_statement for THIS account
// (reconciliation is scoped per-account: a transaction reconciled on one
// side of a transfer isn't automatically reconciled on the other).
func (q *Queries) ListUnreconciledLedgerTransactions(ctx context.Context, arg ListUnreconciledLedgerTransactionsParams) ([]LedgerTransaction, error) {
	rows, err := q.db.Query(ctx, listUnreconciledLedgerTransactions, arg.AccountID, arg.ThroughDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerTransaction
	for rows.Next() {
		var i LedgerTransaction
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.TransactionDate,
			&i.Description,
			&i.ReferenceNumber,
			&i.ReversesLedgerTransactionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumReconciledActivityByStatementIDs = `-- name: SumReconciledActivityByStatementIDs :many
SELECT bs.id AS bank_statement_id,
    lat.normal_balance,
    COALESCE(SUM(le.debit_amount), 0)::numeric AS total_debit,
    COALESCE(SUM(le.credit_amount), 0)::numeric AS total_credit
FROM bank_statement bs
JOIN ledger_account la ON la.id = bs.ledger_account_id
JOIN ledger_account_type lat ON lat.id = la.account_type_id
LEFT JOIN bank_statement_line bsl ON bsl.bank_statement_id = bs.id
LEFT JOIN ledger_entry le ON le.ledger_transaction_id = bsl.ledger_transaction_id
    AND le.account_id = bs.ledger_account_id
    AND le.deleted_at IS NULL
WHERE bs.id = ANY($1::bigint[])
GROUP BY bs.id, lat.normal_balance
`

type SumReconciledActivityByStatementIDsRow struct {
	BankStatementID int64          `json:"bank_statement_id"`
	NormalBalance   string         `json:"normal_balance"`
	TotalDebit      pgtype.Numeric `json:"total_debit"`
	TotalCredit     pgtype.Numeric `json:"total_credit"`
}

// One row per statement: total debit/credit on the statement's own account
// across every ledger_transaction already reconciled to it (linked via
// bank_statement_line), plus that account's normal balance - everything
// reconciled_balance needs, for a whole list of statements in one round trip.
// LEFT JOINs so a statement with no lines yet still gets a zero row.
func (q *Queries) SumReconciledActivityByStatementIDs(ctx context.Context, bankStatementIds []int64) ([]SumReconciledActivityByStatementIDsRow, error) {
	rows, err := q.db.Query(ctx, sumReconciledActivityByStatementIDs, bankStatementIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumReconciledActivityByStatementIDsRow
	for rows.Next() {
		var i SumReconciledActivityByStatementIDsRow
		if err := rows.Scan(
			&i.BankStatementID,
			&i.NormalBalance,
			&i.TotalDebit,
			&i.TotalCredit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBankStatement = `-- name: UpdateBankStatement :one
UPDATE bank_statement SET
    statement_name = COALESCE($1, statement_name),
    statement_date = COALESCE($2, statement_date),
    opening_balance = COALESCE($3, opening_balance),
    closing_balance = COALESCE($4, closing_balance),
    updated_at = NOW()
WHERE id = $5 AND deleted_at IS NULL
    AND ($6::bigint IS NULL OR resource_version = $6)
RETURNING id, business_id, ledger_account_id, statement_name, statement_date, opening_balance, closing_balance, created_by_user_id, created_at, updated_at, deleted_at, resource_version
`

type UpdateBankStatementParams struct {
	StatementName   *string        `json:"statement_name"`
	StatementDate   pgtype.Date    `json:"statement_date"`
	OpeningBalance  pgtype.Numeric `json:"opening_balance"`
	ClosingBalance  pgtype.Numeric `json:"closing_balance"`
	ID              int64          `json:"id"`
	ResourceVersion *int64         `json:"resource_version"`
}

func (q *Queries) UpdateBankStatement(ctx context.Context, arg UpdateBankStatementParams) (BankStatement, error) {
	row := q.db.QueryRow(ctx, updateBankStatement,
		arg.StatementName,
		arg.StatementDate,
		arg.OpeningBalance,
		arg.ClosingBalance,
		arg.ID,
		arg.ResourceVersion,
	)
	var i BankStatement
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LedgerAccountID,
		&i.StatementName,
		&i.StatementDate,
		&i.OpeningBalance,
		&i.ClosingBalance,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ResourceVersion,
	)
	return i, err
}
