// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: business_invite.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptBusinessInvite = `-- name: AcceptBusinessInvite :one
UPDATE business_invite SET accepted_at = NOW(), accepted_by_user_id = $2
WHERE id = $1
RETURNING id, business_id, email, role, token_hash, invited_by_user_id, created_at, expires_at, accepted_at, accepted_by_user_id, revoked_at
`

type AcceptBusinessInviteParams struct {
	ID               int64  `json:"id"`
	AcceptedByUserID *int64 `json:"accepted_by_user_id"`
}

func (q *Queries) AcceptBusinessInvite(ctx context.Context, arg AcceptBusinessInviteParams) (BusinessInvite, error) {
	row := q.db.QueryRow(ctx, acceptBusinessInvite, arg.ID, arg.AcceptedByUserID)
	var i BusinessInvite
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByUserID,
		&i.RevokedAt,
	)
	return i, err
}

const createBusinessInvite = `-- name: CreateBusinessInvite :one

INSERT INTO business_invite (business_id, email, role, token_hash, invited_by_user_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, business_id, email, role, token_hash, invited_by_user_id, created_at, expires_at, accepted_at, accepted_by_user_id, revoked_at
`

type CreateBusinessInviteParams struct {
	BusinessID      int64            `json:"business_id"`
	Email           string           `json:"email"`
	Role            string           `json:"role"`
	TokenHash       string           `json:"token_hash"`
	InvitedByUserID *int64           `json:"invited_by_user_id"`
	ExpiresAt       pgtype.Timestamp `json:"expires_at"`
}

// Copyright (c) 2025 Silver Blueprints LLC
// SPDX-License-Identifier: MIT
func (q *Queries) CreateBusinessInvite(ctx context.Context, arg CreateBusinessInviteParams) (BusinessInvite, error) {
	row := q.db.QueryRow(ctx, createBusinessInvite,
		arg.BusinessID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedByUserID,
		arg.ExpiresAt,
	)
	var i BusinessInvite
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByUserID,
		&i.RevokedAt,
	)
	return i, err
}

const getBusinessInvite = `-- name: GetBusinessInvite :one
SELECT id, business_id, email, role, token_hash, invited_by_user_id, created_at, expires_at, accepted_at, accepted_by_user_id, revoked_at FROM business_invite WHERE id = $1
`

func (q *Queries) GetBusinessInvite(ctx context.Context, id int64) (BusinessInvite, error) {
	row := q.db.QueryRow(ctx, getBusinessInvite, id)
	var i BusinessInvite
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByUserID,
		&i.RevokedAt,
	)
	return i, err
}

const getPendingBusinessInviteByTokenHash = `-- name: GetPendingBusinessInviteByTokenHash :one
SELECT id, business_id, email, role, token_hash, invited_by_user_id, created_at, expires_at, accepted_at, accepted_by_user_id, revoked_at FROM business_invite
WHERE token_hash = $1 AND accepted_at IS NULL AND revoked_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetPendingBusinessInviteByTokenHash(ctx context.Context, tokenHash string) (BusinessInvite, error) {
	row := q.db.QueryRow(ctx, getPendingBusinessInviteByTokenHash, tokenHash)
	var i BusinessInvite
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByUserID,
		&i.RevokedAt,
	)
	return i, err
}

const listBusinessInvitesForBusiness = `-- name: ListBusinessInvitesForBusiness :many
SELECT id, business_id, email, role, token_hash, invited_by_user_id, created_at, expires_at, accepted_at, accepted_by_user_id, revoked_at FROM business_invite WHERE business_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListBusinessInvitesForBusiness(ctx context.Context, businessID int64) ([]BusinessInvite, error) {
	rows, err := q.db.Query(ctx, listBusinessInvitesForBusiness, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BusinessInvite
	for rows.Next() {
		var i BusinessInvite
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedByUserID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.AcceptedByUserID,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeBusinessInvite = `-- name: RevokeBusinessInvite :one
UPDATE business_invite SET revoked_at = NOW()
WHERE id = $1 AND accepted_at IS NULL AND revoked_at IS NULL
RETURNING id, business_id, email, role, token_hash, invited_by_user_id, created_at, expires_at, accepted_at, accepted_by_user_id, revoked_at
`

func (q *Queries) RevokeBusinessInvite(ctx context.Context, id int64) (BusinessInvite, error) {
	row := q.db.QueryRow(ctx, revokeBusinessInvite, id)
	var i BusinessInvite
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByUserID,
		&i.RevokedAt,
	)
	return i, err
}
