// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: context.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearSupersededBy = `-- name: ClearSupersededBy :exec
UPDATE entity_context SET superseded_by_id = NULL, updated_at = NOW()
WHERE superseded_by_id = $1::bigint AND deleted_at IS NULL
`

// Run alongside DeleteEntityContext: notes the deleted row superseded
// become current again, rather than staying hidden behind a dead pointer
// (ListEntityContextForEntity filters superseded_by_id IS NULL by default).
func (q *Queries) ClearSupersededBy(ctx context.Context, deletedID int64) error {
	_, err := q.db.Exec(ctx, clearSupersededBy, deletedID)
	return err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachment (
    business_id, entity_type, entity_id, original_filename, storage_key,
    content_type, file_size_bytes, display_sequence, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, business_id, entity_type, entity_id, original_filename, storage_key, content_type, file_size_bytes, display_sequence, created_by_user_id, created_at, deleted_at
`

type CreateAttachmentParams struct {
	BusinessID       int64   `json:"business_id"`
	EntityType       string  `json:"entity_type"`
	EntityID         int64   `json:"entity_id"`
	OriginalFilename *string `json:"original_filename"`
	StorageKey       string  `json:"storage_key"`
	ContentType      *string `json:"content_type"`
	FileSizeBytes    *int64  `json:"file_size_bytes"`
	DisplaySequence  int32   `json:"display_sequence"`
	CreatedByUserID  *int64  `json:"created_by_user_id"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.BusinessID,
		arg.EntityType,
		arg.EntityID,
		arg.OriginalFilename,
		arg.StorageKey,
		arg.ContentType,
		arg.FileSizeBytes,
		arg.DisplaySequence,
		arg.CreatedByUserID,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.EntityType,
		&i.EntityID,
		&i.OriginalFilename,
		&i.StorageKey,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.DisplaySequence,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createEntityContext = `-- name: CreateEntityContext :one

INSERT INTO entity_context (
    business_id, entity_type, entity_id, context_type, content, metadata,
    source, confidence, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, business_id, entity_type, entity_id, context_type, content, metadata, source, confidence, superseded_by_id, created_by_user_id, created_at, updated_at, deleted_at
`

type CreateEntityContextParams struct {
	BusinessID      int64          `json:"business_id"`
	EntityType      string         `json:"entity_type"`
	EntityID        int64          `json:"entity_id"`
	ContextType     string         `json:"context_type"`
	Content         string         `json:"content"`
	Metadata        []byte         `json:"metadata"`
	Source          *string        `json:"source"`
	Confidence      pgtype.Numeric `json:"confidence"`
	CreatedByUserID *int64         `json:"created_by_user_id"`
}

// Copyright (c) 2025 Silver Blueprints LLC
// SPDX-License-Identifier: MIT
func (q *Queries) CreateEntityContext(ctx context.Context, arg CreateEntityContextParams) (EntityContext, error) {
	row := q.db.QueryRow(ctx, createEntityContext,
		arg.BusinessID,
		arg.EntityType,
		arg.EntityID,
		arg.ContextType,
		arg.Content,
		arg.Metadata,
		arg.Source,
		arg.Confidence,
		arg.CreatedByUserID,
	)
	var i EntityContext
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.EntityType,
		&i.EntityID,
		&i.ContextType,
		&i.Content,
		&i.Metadata,
		&i.Source,
		&i.Confidence,
		&i.SupersededByID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :one
UPDATE attachment SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, business_id, entity_type, entity_id, original_filename, storage_key, content_type, file_size_bytes, display_sequence, created_by_user_id, created_at, deleted_at
`

func (q *Queries) DeleteAttachment(ctx context.Context, id int64) (Attachment, error) {
	row := q.db.QueryRow(ctx, deleteAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.EntityType,
		&i.EntityID,
		&i.OriginalFilename,
		&i.StorageKey,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.DisplaySequence,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEntityContext = `-- name: DeleteEntityContext :one
UPDATE entity_context SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, business_id, entity_type, entity_id, context_type, content, metadata, source, confidence, superseded_by_id, created_by_user_id, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteEntityContext(ctx context.Context, id int64) (EntityContext, error) {
	row := q.db.QueryRow(ctx, deleteEntityContext, id)
	var i EntityContext
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.EntityType,
		&i.EntityID,
		&i.ContextType,
		&i.Content,
		&i.Metadata,
		&i.Source,
		&i.Confidence,
		&i.SupersededByID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT id, business_id, entity_type, entity_id, original_filename, storage_key, content_type, file_size_bytes, display_sequence, created_by_user_id, created_at, deleted_at FROM attachment WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAttachment(ctx context.Context, id int64) (Attachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.EntityType,
		&i.EntityID,
		&i.OriginalFilename,
		&i.StorageKey,
		&i.ContentType,
		&i.FileSizeBytes,
		&i.DisplaySequence,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEntityContext = `-- name: GetEntityContext :one
SELECT id, business_id, entity_type, entity_id, context_type, content, metadata, source, confidence, superseded_by_id, created_by_user_id, created_at, updated_at, deleted_at FROM entity_context WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetEntityContext(ctx context.Context, id int64) (EntityContext, error) {
	row := q.db.QueryRow(ctx, getEntityContext, id)
	var i EntityContext
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.EntityType,
		&i.EntityID,
		&i.ContextType,
		&i.Content,
		&i.Metadata,
		&i.Source,
		&i.Confidence,
		&i.SupersededByID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAttachmentsForEntity = `-- name: ListAttachmentsForEntity :many
SELECT id, business_id, entity_type, entity_id, original_filename, storage_key, content_type, file_size_bytes, display_sequence, created_by_user_id, created_at, deleted_at FROM attachment
WHERE business_id = $1 AND entity_type = $2 AND entity_id = $3 AND deleted_at IS NULL
ORDER BY display_sequence, id
`

type ListAttachmentsForEntityParams struct {
	BusinessID int64  `json:"business_id"`
	EntityType string `json:"entity_type"`
	EntityID   int64  `json:"entity_id"`
}

func (q *Queries) ListAttachmentsForEntity(ctx context.Context, arg ListAttachmentsForEntityParams) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentsForEntity, arg.BusinessID, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.EntityType,
			&i.EntityID,
			&i.OriginalFilename,
			&i.StorageKey,
			&i.ContentType,
			&i.FileSizeBytes,
			&i.DisplaySequence,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityContextForEntity = `-- name: ListEntityContextForEntity :many
SELECT id, business_id, entity_type, entity_id, context_type, content, metadata, source, confidence, superseded_by_id, created_by_user_id, created_at, updated_at, deleted_at FROM entity_context
WHERE business_id = $1
    AND entity_type = $2
    AND entity_id = $3
    AND deleted_at IS NULL
    AND ($4::boolean OR superseded_by_id IS NULL)
ORDER BY created_at DESC
`

type ListEntityContextForEntityParams struct {
	BusinessID        int64  `json:"business_id"`
	EntityType        string `json:"entity_type"`
	EntityID          int64  `json:"entity_id"`
	IncludeSuperseded bool   `json:"include_superseded"`
}

func (q *Queries) ListEntityContextForEntity(ctx context.Context, arg ListEntityContextForEntityParams) ([]EntityContext, error) {
	rows, err := q.db.Query(ctx, listEntityContextForEntity,
		arg.BusinessID,
		arg.EntityType,
		arg.EntityID,
		arg.IncludeSuperseded,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityContext
	for rows.Next() {
		var i EntityContext
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.EntityType,
			&i.EntityID,
			&i.ContextType,
			&i.Content,
			&i.Metadata,
			&i.Source,
			&i.Confidence,
			&i.SupersededByID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const supersedeEntityContext = `-- name: SupersedeEntityContext :exec
UPDATE entity_context SET superseded_by_id = $2, updated_at = NOW()
WHERE id = $1
`

type SupersedeEntityContextParams struct {
	ID             int64  `json:"id"`
	SupersededByID *int64 `json:"superseded_by_id"`
}

func (q *Queries) SupersedeEntityContext(ctx context.Context, arg SupersedeEntityContextParams) error {
	_, err := q.db.Exec(ctx, supersedeEntityContext, arg.ID, arg.SupersededByID)
	return err
}
