// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credential_enrollment.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeCredentialEnrollment = `-- name: ConsumeCredentialEnrollment :exec
UPDATE credential_enrollment SET consumed_at = NOW()
WHERE id = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumeCredentialEnrollment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, consumeCredentialEnrollment, id)
	return err
}

const createCredentialEnrollment = `-- name: CreateCredentialEnrollment :one

INSERT INTO credential_enrollment (user_id, token_hash, revoke_existing, purpose, created_by_user_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id) WHERE consumed_at IS NULL
DO UPDATE SET
    token_hash = EXCLUDED.token_hash,
    revoke_existing = EXCLUDED.revoke_existing,
    purpose = EXCLUDED.purpose,
    created_by_user_id = EXCLUDED.created_by_user_id,
    created_at = NOW(),
    expires_at = EXCLUDED.expires_at
RETURNING id, user_id, token_hash, revoke_existing, purpose, created_by_user_id, created_at, expires_at, consumed_at
`

type CreateCredentialEnrollmentParams struct {
	UserID          int64            `json:"user_id"`
	TokenHash       string           `json:"token_hash"`
	RevokeExisting  bool             `json:"revoke_existing"`
	Purpose         string           `json:"purpose"`
	CreatedByUserID *int64           `json:"created_by_user_id"`
	ExpiresAt       pgtype.Timestamp `json:"expires_at"`
}

// Copyright (c) 2025 Silver Blueprints LLC
// SPDX-License-Identifier: MIT
// Upsert on the one-live-token-per-user rule (credential_enrollment_user_pending_uindex):
// issuing a fresh enrollment for a user who already has a pending one invalidates the old one
// by replacing its hash, so only the newest token ever works.
func (q *Queries) CreateCredentialEnrollment(ctx context.Context, arg CreateCredentialEnrollmentParams) (CredentialEnrollment, error) {
	row := q.db.QueryRow(ctx, createCredentialEnrollment,
		arg.UserID,
		arg.TokenHash,
		arg.RevokeExisting,
		arg.Purpose,
		arg.CreatedByUserID,
		arg.ExpiresAt,
	)
	var i CredentialEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.RevokeExisting,
		&i.Purpose,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getPendingCredentialEnrollmentByTokenHash = `-- name: GetPendingCredentialEnrollmentByTokenHash :one
SELECT id, user_id, token_hash, revoke_existing, purpose, created_by_user_id, created_at, expires_at, consumed_at FROM credential_enrollment
WHERE token_hash = $1 AND consumed_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetPendingCredentialEnrollmentByTokenHash(ctx context.Context, tokenHash string) (CredentialEnrollment, error) {
	row := q.db.QueryRow(ctx, getPendingCredentialEnrollmentByTokenHash, tokenHash)
	var i CredentialEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.RevokeExisting,
		&i.Purpose,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getPendingCredentialEnrollmentForUser = `-- name: GetPendingCredentialEnrollmentForUser :one
SELECT id, user_id, token_hash, revoke_existing, purpose, created_by_user_id, created_at, expires_at, consumed_at FROM credential_enrollment
WHERE user_id = $1 AND consumed_at IS NULL AND expires_at > NOW()
`

func (q *Queries) GetPendingCredentialEnrollmentForUser(ctx context.Context, userID int64) (CredentialEnrollment, error) {
	row := q.db.QueryRow(ctx, getPendingCredentialEnrollmentForUser, userID)
	var i CredentialEnrollment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.RevokeExisting,
		&i.Purpose,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}
