// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ledger.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerAccount = `-- name: CreateLedgerAccount :one

INSERT INTO ledger_account (
    business_id, account_type_id, parent_account_id, code, name, description,
    is_system, is_reconcilable, is_container, cash_flow_category_id,
    balance_sheet_category_id, income_statement_category_id, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, business_id, account_type_id, code, name, description, parent_account_id, is_system, is_reconcilable, is_container, display_sequence, cash_flow_category_id, balance_sheet_category_id, income_statement_category_id, is_active, created_by_user_id, created_at, updated_at, resource_version
`

type CreateLedgerAccountParams struct {
	BusinessID                int64   `json:"business_id"`
	AccountTypeID             int32   `json:"account_type_id"`
	ParentAccountID           *int32  `json:"parent_account_id"`
	Code                      string  `json:"code"`
	Name                      string  `json:"name"`
	Description               *string `json:"description"`
	IsSystem                  bool    `json:"is_system"`
	IsReconcilable            bool    `json:"is_reconcilable"`
	IsContainer               bool    `json:"is_container"`
	CashFlowCategoryID        *int32  `json:"cash_flow_category_id"`
	BalanceSheetCategoryID    *int32  `json:"balance_sheet_category_id"`
	IncomeStatementCategoryID *int32  `json:"income_statement_category_id"`
	CreatedByUserID           *int64  `json:"created_by_user_id"`
}

// Copyright (c) 2025 Silver Blueprints LLC
// SPDX-License-Identifier: MIT
func (q *Queries) CreateLedgerAccount(ctx context.Context, arg CreateLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, createLedgerAccount,
		arg.BusinessID,
		arg.AccountTypeID,
		arg.ParentAccountID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.IsSystem,
		arg.IsReconcilable,
		arg.IsContainer,
		arg.CashFlowCategoryID,
		arg.BalanceSheetCategoryID,
		arg.IncomeStatementCategoryID,
		arg.CreatedByUserID,
	)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.AccountTypeID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ParentAccountID,
		&i.IsSystem,
		&i.IsReconcilable,
		&i.IsContainer,
		&i.DisplaySequence,
		&i.CashFlowCategoryID,
		&i.BalanceSheetCategoryID,
		&i.IncomeStatementCategoryID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
	)
	return i, err
}

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entry (
    business_id, ledger_transaction_id, account_id, debit_amount, credit_amount, description
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, business_id, ledger_transaction_id, account_id, debit_amount, credit_amount, description, created_at, updated_at, deleted_at
`

type CreateLedgerEntryParams struct {
	BusinessID          int64          `json:"business_id"`
	LedgerTransactionID int64          `json:"ledger_transaction_id"`
	AccountID           int32          `json:"account_id"`
	DebitAmount         pgtype.Numeric `json:"debit_amount"`
	CreditAmount        pgtype.Numeric `json:"credit_amount"`
	Description         *string        `json:"description"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.BusinessID,
		arg.LedgerTransactionID,
		arg.AccountID,
		arg.DebitAmount,
		arg.CreditAmount,
		arg.Description,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.LedgerTransactionID,
		&i.AccountID,
		&i.DebitAmount,
		&i.CreditAmount,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLedgerTransaction = `-- name: CreateLedgerTransaction :one
INSERT INTO ledger_transaction (
    business_id, transaction_date, description, reference_number, created_by_user_id,
    reverses_ledger_transaction_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, business_id, transaction_date, description, reference_number, reverses_ledger_transaction_id, created_by_user_id, created_at, updated_at, deleted_at
`

type CreateLedgerTransactionParams struct {
	BusinessID                  int64       `json:"business_id"`
	TransactionDate             pgtype.Date `json:"transaction_date"`
	Description                 *string     `json:"description"`
	ReferenceNumber             *string     `json:"reference_number"`
	CreatedByUserID             *int64      `json:"created_by_user_id"`
	ReversesLedgerTransactionID *int64      `json:"reverses_ledger_transaction_id"`
}

func (q *Queries) CreateLedgerTransaction(ctx context.Context, arg CreateLedgerTransactionParams) (LedgerTransaction, error) {
	row := q.db.QueryRow(ctx, createLedgerTransaction,
		arg.BusinessID,
		arg.TransactionDate,
		arg.Description,
		arg.ReferenceNumber,
		arg.CreatedByUserID,
		arg.ReversesLedgerTransactionID,
	)
	var i LedgerTransaction
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.TransactionDate,
		&i.Description,
		&i.ReferenceNumber,
		&i.ReversesLedgerTransactionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateLedgerAccount = `-- name: DeactivateLedgerAccount :one
UPDATE ledger_account SET is_active = FALSE, updated_at = NOW()
WHERE id = $1
    AND ($2::bigint IS NULL OR resource_version = $2)
RETURNING id, business_id, account_type_id, code, name, description, parent_account_id, is_system, is_reconcilable, is_container, display_sequence, cash_flow_category_id, balance_sheet_category_id, income_statement_category_id, is_active, created_by_user_id, created_at, updated_at, resource_version
`

type DeactivateLedgerAccountParams struct {
	ID              int32  `json:"id"`
	ResourceVersion *int64 `json:"resource_version"`
}

func (q *Queries) DeactivateLedgerAccount(ctx context.Context, arg DeactivateLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, deactivateLedgerAccount, arg.ID, arg.ResourceVersion)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.AccountTypeID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ParentAccountID,
		&i.IsSystem,
		&i.IsReconcilable,
		&i.IsContainer,
		&i.DisplaySequence,
		&i.CashFlowCategoryID,
		&i.BalanceSheetCategoryID,
		&i.IncomeStatementCategoryID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
	)
	return i, err
}

const getLedgerAccount = `-- name: GetLedgerAccount :one
SELECT id, business_id, account_type_id, code, name, description, parent_account_id, is_system, is_reconcilable, is_container, display_sequence, cash_flow_category_id, balance_sheet_category_id, income_statement_category_id, is_active, created_by_user_id, created_at, updated_at, resource_version FROM ledger_account WHERE id = $1
`

func (q *Queries) GetLedgerAccount(ctx context.Context, id int32) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccount, id)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.AccountTypeID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ParentAccountID,
		&i.IsSystem,
		&i.IsReconcilable,
		&i.IsContainer,
		&i.DisplaySequence,
		&i.CashFlowCategoryID,
		&i.BalanceSheetCategoryID,
		&i.IncomeStatementCategoryID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
	)
	return i, err
}

const getLedgerAccountByCode = `-- name: GetLedgerAccountByCode :one
SELECT id, business_id, account_type_id, code, name, description, parent_account_id, is_system, is_reconcilable, is_container, display_sequence, cash_flow_category_id, balance_sheet_category_id, income_statement_category_id, is_active, created_by_user_id, created_at, updated_at, resource_version FROM ledger_account WHERE business_id = $1 AND code = $2
`

type GetLedgerAccountByCodeParams struct {
	BusinessID int64  `json:"business_id"`
	Code       string `json:"code"`
}

func (q *Queries) GetLedgerAccountByCode(ctx context.Context, arg GetLedgerAccountByCodeParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccountByCode, arg.BusinessID, arg.Code)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.AccountTypeID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ParentAccountID,
		&i.IsSystem,
		&i.IsReconcilable,
		&i.IsContainer,
		&i.DisplaySequence,
		&i.CashFlowCategoryID,
		&i.BalanceSheetCategoryID,
		&i.IncomeStatementCategoryID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
	)
	return i, err
}

const getLedgerAccountType = `-- name: GetLedgerAccountType :one
SELECT id, name, description, normal_balance, created_at, updated_at FROM ledger_account_type WHERE id = $1
`

func (q *Queries) GetLedgerAccountType(ctx context.Context, id int32) (LedgerAccountType, error) {
	row := q.db.QueryRow(ctx, getLedgerAccountType, id)
	var i LedgerAccountType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.NormalBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLedgerTransaction = `-- name: GetLedgerTransaction :one
SELECT id, business_id, transaction_date, description, reference_number, reverses_ledger_transaction_id, created_by_user_id, created_at, updated_at, deleted_at FROM ledger_transaction WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLedgerTransaction(ctx context.Context, id int64) (LedgerTransaction, error) {
	row := q.db.QueryRow(ctx, getLedgerTransaction, id)
	var i LedgerTransaction
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.TransactionDate,
		&i.Description,
		&i.ReferenceNumber,
		&i.ReversesLedgerTransactionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReversalOfLedgerTransaction = `-- name: GetReversalOfLedgerTransaction :one
SELECT id, business_id, transaction_date, description, reference_number, reverses_ledger_transaction_id, created_by_user_id, created_at, updated_at, deleted_at FROM ledger_transaction
WHERE reverses_ledger_transaction_id = $1::bigint AND deleted_at IS NULL
`

// The transaction that reverses $1, if one has been posted. The partial
// unique index on reverses_ledger_transaction_id guarantees at most one.
func (q *Queries) GetReversalOfLedgerTransaction(ctx context.Context, originalID int64) (LedgerTransaction, error) {
	row := q.db.QueryRow(ctx, getReversalOfLedgerTransaction, originalID)
	var i LedgerTransaction
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.TransactionDate,
		&i.Description,
		&i.ReferenceNumber,
		&i.ReversesLedgerTransactionID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLedgerAccounts = `-- name: ListLedgerAccounts :many
SELECT id, business_id, account_type_id, code, name, description, parent_account_id, is_system, is_reconcilable, is_container, display_sequence, cash_flow_category_id, balance_sheet_category_id, income_statement_category_id, is_active, created_by_user_id, created_at, updated_at, resource_version FROM ledger_account WHERE business_id = $1 ORDER BY code
`

func (q *Queries) ListLedgerAccounts(ctx context.Context, businessID int64) ([]LedgerAccount, error) {
	rows, err := q.db.Query(ctx, listLedgerAccounts, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerAccount
	for rows.Next() {
		var i LedgerAccount
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.AccountTypeID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.ParentAccountID,
			&i.IsSystem,
			&i.IsReconcilable,
			&i.IsContainer,
			&i.DisplaySequence,
			&i.CashFlowCategoryID,
			&i.BalanceSheetCategoryID,
			&i.IncomeStatementCategoryID,
			&i.IsActive,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByTransaction = `-- name: ListLedgerEntriesByTransaction :many
SELECT id, business_id, ledger_transaction_id, account_id, debit_amount, credit_amount, description, created_at, updated_at, deleted_at FROM ledger_entry WHERE ledger_transaction_id = $1 AND deleted_at IS NULL ORDER BY id
`

func (q *Queries) ListLedgerEntriesByTransaction(ctx context.Context, ledgerTransactionID int64) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByTransaction, ledgerTransactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.LedgerTransactionID,
			&i.AccountID,
			&i.DebitAmount,
			&i.CreditAmount,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByTransactionIDs = `-- name: ListLedgerEntriesByTransactionIDs :many
SELECT id, business_id, ledger_transaction_id, account_id, debit_amount, credit_amount, description, created_at, updated_at, deleted_at FROM ledger_entry WHERE ledger_transaction_id = ANY($1::bigint[]) AND deleted_at IS NULL ORDER BY id
`

func (q *Queries) ListLedgerEntriesByTransactionIDs(ctx context.Context, transactionIds []int64) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByTransactionIDs, transactionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.LedgerTransactionID,
			&i.AccountID,
			&i.DebitAmount,
			&i.CreditAmount,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerTransactions = `-- name: ListLedgerTransactions :many
SELECT lt.id, lt.business_id, lt.transaction_date, lt.description, lt.reference_number, lt.reverses_ledger_transaction_id, lt.created_by_user_id, lt.created_at, lt.updated_at, lt.deleted_at FROM ledger_transaction lt
WHERE lt.business_id = $1 AND lt.deleted_at IS NULL
  AND (lt.transaction_date, lt.id) < ($2::date, $3::bigint)
  AND ($4::date IS NULL OR lt.transaction_date >= $4)
  AND ($5::date IS NULL OR lt.transaction_date <= $5)
  AND ($6::text IS NULL
       OR lt.description ILIKE '%' || $6 || '%')
  AND ($7::int IS NULL OR EXISTS (
        SELECT 1 FROM ledger_entry le
        WHERE le.ledger_transaction_id = lt.id AND le.account_id = $7
          AND le.deleted_at IS NULL))
ORDER BY lt.transaction_date DESC, lt.id DESC
LIMIT $8
`

type ListLedgerTransactionsParams struct {
	BusinessID          int64       `json:"business_id"`
	BeforeDate          pgtype.Date `json:"before_date"`
	BeforeID            int64       `json:"before_id"`
	StartDate           pgtype.Date `json:"start_date"`
	EndDate             pgtype.Date `json:"end_date"`
	DescriptionContains *string     `json:"description_contains"`
	AccountID           *int32      `json:"account_id"`
	PageLimit           int32       `json:"page_limit"`
}

// Keyset-paged on (transaction_date, id) DESC — a compound cursor, not id
// alone, so pagination reflects the chronological order clients want to
// show rather than posting order. (transaction_date, id) is unique per
// row, which is what keyset pagination needs. Also takes optional
// AND-combined filters: a date range on transaction_date, a
// case-insensitive substring of the transaction description, and "has a
// live entry against this account".
func (q *Queries) ListLedgerTransactions(ctx context.Context, arg ListLedgerTransactionsParams) ([]LedgerTransaction, error) {
	rows, err := q.db.Query(ctx, listLedgerTransactions,
		arg.BusinessID,
		arg.BeforeDate,
		arg.BeforeID,
		arg.StartDate,
		arg.EndDate,
		arg.DescriptionContains,
		arg.AccountID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerTransaction
	for rows.Next() {
		var i LedgerTransaction
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.TransactionDate,
			&i.Description,
			&i.ReferenceNumber,
			&i.ReversesLedgerTransactionID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLedgerEntriesByTransaction = `-- name: SoftDeleteLedgerEntriesByTransaction :exec
UPDATE ledger_entry SET deleted_at = NOW()
WHERE ledger_transaction_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteLedgerEntriesByTransaction(ctx context.Context, ledgerTransactionID int64) error {
	_, err := q.db.Exec(ctx, softDeleteLedgerEntriesByTransaction, ledgerTransactionID)
	return err
}

const updateLedgerAccount = `-- name: UpdateLedgerAccount :one
UPDATE ledger_account SET
    name = COALESCE($1, name),
    description = COALESCE($2, description),
    is_reconcilable = COALESCE($3, is_reconcilable),
    is_container = COALESCE($4, is_container),
    cash_flow_category_id = COALESCE($5, cash_flow_category_id),
    balance_sheet_category_id = COALESCE($6, balance_sheet_category_id),
    income_statement_category_id = COALESCE($7, income_statement_category_id),
    updated_at = NOW()
WHERE id = $8
    AND ($9::bigint IS NULL OR resource_version = $9)
RETURNING id, business_id, account_type_id, code, name, description, parent_account_id, is_system, is_reconcilable, is_container, display_sequence, cash_flow_category_id, balance_sheet_category_id, income_statement_category_id, is_active, created_by_user_id, created_at, updated_at, resource_version
`

type UpdateLedgerAccountParams struct {
	Name                      *string `json:"name"`
	Description               *string `json:"description"`
	IsReconcilable            *bool   `json:"is_reconcilable"`
	IsContainer               *bool   `json:"is_container"`
	CashFlowCategoryID        *int32  `json:"cash_flow_category_id"`
	BalanceSheetCategoryID    *int32  `json:"balance_sheet_category_id"`
	IncomeStatementCategoryID *int32  `json:"income_statement_category_id"`
	ID                        int32   `json:"id"`
	ResourceVersion           *int64  `json:"resource_version"`
}

func (q *Queries) UpdateLedgerAccount(ctx context.Context, arg UpdateLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, updateLedgerAccount,
		arg.Name,
		arg.Description,
		arg.IsReconcilable,
		arg.IsContainer,
		arg.CashFlowCategoryID,
		arg.BalanceSheetCategoryID,
		arg.IncomeStatementCategoryID,
		arg.ID,
		arg.ResourceVersion,
	)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.AccountTypeID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.ParentAccountID,
		&i.IsSystem,
		&i.IsReconcilable,
		&i.IsContainer,
		&i.DisplaySequence,
		&i.CashFlowCategoryID,
		&i.BalanceSheetCategoryID,
		&i.IncomeStatementCategoryID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
	)
	return i, err
}
