// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppUser struct {
	ID            int64            `json:"id"`
	Email         string           `json:"email"`
	DisplayName   *string          `json:"display_name"`
	IsGlobalAdmin bool             `json:"is_global_admin"`
	IsActive      bool             `json:"is_active"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
}

type Attachment struct {
	ID               int64            `json:"id"`
	BusinessID       int64            `json:"business_id"`
	EntityType       string           `json:"entity_type"`
	EntityID         int64            `json:"entity_id"`
	OriginalFilename *string          `json:"original_filename"`
	StorageKey       string           `json:"storage_key"`
	ContentType      *string          `json:"content_type"`
	FileSizeBytes    *int64           `json:"file_size_bytes"`
	DisplaySequence  int32            `json:"display_sequence"`
	CreatedByUserID  *int64           `json:"created_by_user_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	DeletedAt        pgtype.Timestamp `json:"deleted_at"`
}

type BalanceSheetCategory struct {
	ID              int32  `json:"id"`
	Name            string `json:"name"`
	DisplaySequence int32  `json:"display_sequence"`
}

type BankStatement struct {
	ID              int64            `json:"id"`
	BusinessID      int64            `json:"business_id"`
	LedgerAccountID int32            `json:"ledger_account_id"`
	StatementName   string           `json:"statement_name"`
	StatementDate   pgtype.Date      `json:"statement_date"`
	OpeningBalance  pgtype.Numeric   `json:"opening_balance"`
	ClosingBalance  pgtype.Numeric   `json:"closing_balance"`
	CreatedByUserID *int64           `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	DeletedAt       pgtype.Timestamp `json:"deleted_at"`
	ResourceVersion int64            `json:"resource_version"`
}

type BankStatementLine struct {
	ID                  int64            `json:"id"`
	BankStatementID     int64            `json:"bank_statement_id"`
	LedgerTransactionID int64            `json:"ledger_transaction_id"`
	DisplaySequence     int32            `json:"display_sequence"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
}

type Business struct {
	ID                        int64            `json:"id"`
	Name                      string           `json:"name"`
	TaxID                     *string          `json:"tax_id"`
	AddressLine1              *string          `json:"address_line1"`
	AddressLine2              *string          `json:"address_line2"`
	City                      *string          `json:"city"`
	State                     *string          `json:"state"`
	PostalCode                *string          `json:"postal_code"`
	Country                   *string          `json:"country"`
	Phone                     *string          `json:"phone"`
	Email                     *string          `json:"email"`
	WebsiteUrl                *string          `json:"website_url"`
	LogoUrl                   *string          `json:"logo_url"`
	DefaultPaymentTermsDays   *int32           `json:"default_payment_terms_days"`
	DefaultTaxRate            pgtype.Numeric   `json:"default_tax_rate"`
	DefaultInvoiceTerms       *string          `json:"default_invoice_terms"`
	DefaultEstimateTerms      *string          `json:"default_estimate_terms"`
	InvoiceNumberPrefix       *string          `json:"invoice_number_prefix"`
	EstimateNumberPrefix      *string          `json:"estimate_number_prefix"`
	NextInvoiceNumber         *int32           `json:"next_invoice_number"`
	NextEstimateNumber        *int32           `json:"next_estimate_number"`
	Timezone                  *string          `json:"timezone"`
	CurrencyCode              *string          `json:"currency_code"`
	ArAccountID               *int32           `json:"ar_account_id"`
	ApAccountID               *int32           `json:"ap_account_id"`
	IncomeSummaryAccountID    *int32           `json:"income_summary_account_id"`
	RetainedEarningsAccountID *int32           `json:"retained_earnings_account_id"`
	IsActive                  bool             `json:"is_active"`
	CreatedByUserID           *int64           `json:"created_by_user_id"`
	CreatedAt                 pgtype.Timestamp `json:"created_at"`
	UpdatedAt                 pgtype.Timestamp `json:"updated_at"`
	ResourceVersion           int64            `json:"resource_version"`
	DeletedAt                 pgtype.Timestamp `json:"deleted_at"`
}

type BusinessInvite struct {
	ID               int64            `json:"id"`
	BusinessID       int64            `json:"business_id"`
	Email            string           `json:"email"`
	Role             string           `json:"role"`
	TokenHash        string           `json:"token_hash"`
	InvitedByUserID  *int64           `json:"invited_by_user_id"`
	CreatedAt        pgtype.Timestamp `json:"created_at"`
	ExpiresAt        pgtype.Timestamp `json:"expires_at"`
	AcceptedAt       pgtype.Timestamp `json:"accepted_at"`
	AcceptedByUserID *int64           `json:"accepted_by_user_id"`
	RevokedAt        pgtype.Timestamp `json:"revoked_at"`
}

type BusinessUser struct {
	ID         int64            `json:"id"`
	BusinessID int64            `json:"business_id"`
	UserID     int64            `json:"user_id"`
	Role       string           `json:"role"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type CashFlowCategory struct {
	ID              int32  `json:"id"`
	Name            string `json:"name"`
	DisplaySequence int32  `json:"display_sequence"`
}

type Contact struct {
	ID                   int64            `json:"id"`
	BusinessID           int64            `json:"business_id"`
	ContactNumber        string           `json:"contact_number"`
	Name                 string           `json:"name"`
	Email                *string          `json:"email"`
	Phone                *string          `json:"phone"`
	BillingAddressLine1  *string          `json:"billing_address_line1"`
	BillingAddressLine2  *string          `json:"billing_address_line2"`
	BillingCity          *string          `json:"billing_city"`
	BillingState         *string          `json:"billing_state"`
	BillingPostalCode    *string          `json:"billing_postal_code"`
	BillingCountry       *string          `json:"billing_country"`
	ShippingAddressLine1 *string          `json:"shipping_address_line1"`
	ShippingAddressLine2 *string          `json:"shipping_address_line2"`
	ShippingCity         *string          `json:"shipping_city"`
	ShippingState        *string          `json:"shipping_state"`
	ShippingPostalCode   *string          `json:"shipping_postal_code"`
	ShippingCountry      *string          `json:"shipping_country"`
	PaymentTermsDays     *int32           `json:"payment_terms_days"`
	CreditLimit          pgtype.Numeric   `json:"credit_limit"`
	IsActive             bool             `json:"is_active"`
	CreatedByUserID      *int64           `json:"created_by_user_id"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	ResourceVersion      int64            `json:"resource_version"`
	DeletedAt            pgtype.Timestamp `json:"deleted_at"`
}

type Customer struct {
	ID              int64            `json:"id"`
	ContactID       int64            `json:"contact_id"`
	LedgerAccountID *int32           `json:"ledger_account_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type EntityContext struct {
	ID              int64            `json:"id"`
	BusinessID      int64            `json:"business_id"`
	EntityType      string           `json:"entity_type"`
	EntityID        int64            `json:"entity_id"`
	ContextType     string           `json:"context_type"`
	Content         string           `json:"content"`
	Metadata        []byte           `json:"metadata"`
	Source          *string          `json:"source"`
	Confidence      pgtype.Numeric   `json:"confidence"`
	SupersededByID  *int64           `json:"superseded_by_id"`
	CreatedByUserID *int64           `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	DeletedAt       pgtype.Timestamp `json:"deleted_at"`
}

type Estimate struct {
	ID              int64            `json:"id"`
	BusinessID      int64            `json:"business_id"`
	CustomerID      int64            `json:"customer_id"`
	EstimateNumber  string           `json:"estimate_number"`
	EstimateDate    pgtype.Date      `json:"estimate_date"`
	ExpirationDate  pgtype.Date      `json:"expiration_date"`
	Subtotal        pgtype.Numeric   `json:"subtotal"`
	TotalTaxAmount  pgtype.Numeric   `json:"total_tax_amount"`
	TotalAmount     pgtype.Numeric   `json:"total_amount"`
	Status          string           `json:"status"`
	Notes           *string          `json:"notes"`
	Terms           *string          `json:"terms"`
	CreatedByUserID *int64           `json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	ResourceVersion int64            `json:"resource_version"`
	DeletedAt       pgtype.Timestamp `json:"deleted_at"`
}

type EstimateLineItem struct {
	ID           int64            `json:"id"`
	EstimateID   int64            `json:"estimate_id"`
	ItemID       *int64           `json:"item_id"`
	LineNumber   int32            `json:"line_number"`
	Description  string           `json:"description"`
	Quantity     pgtype.Numeric   `json:"quantity"`
	UnitPrice    pgtype.Numeric   `json:"unit_price"`
	LineSubtotal pgtype.Numeric   `json:"line_subtotal"`
	IsTaxable    bool             `json:"is_taxable"`
	TaxRateID    *int64           `json:"tax_rate_id"`
	TaxRate      pgtype.Numeric   `json:"tax_rate"`
	TaxAmount    pgtype.Numeric   `json:"tax_amount"`
	LineTotal    pgtype.Numeric   `json:"line_total"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	DeletedAt    pgtype.Timestamp `json:"deleted_at"`
}

type IncomeStatementCategory struct {
	ID              int32  `json:"id"`
	Name            string `json:"name"`
	DisplaySequence int32  `json:"display_sequence"`
}

type Invoice struct {
	ID                  int64            `json:"id"`
	BusinessID          int64            `json:"business_id"`
	ContactID           int64            `json:"contact_id"`
	InvoiceType         string           `json:"invoice_type"`
	EstimateID          *int64           `json:"estimate_id"`
	InvoiceNumber       string           `json:"invoice_number"`
	InvoiceDate         pgtype.Date      `json:"invoice_date"`
	DueDate             pgtype.Date      `json:"due_date"`
	Subtotal            pgtype.Numeric   `json:"subtotal"`
	TotalTaxAmount      pgtype.Numeric   `json:"total_tax_amount"`
	TotalAmount         pgtype.Numeric   `json:"total_amount"`
	PaidAmount          pgtype.Numeric   `json:"paid_amount"`
	BalanceDue          pgtype.Numeric   `json:"balance_due"`
	Status              string           `json:"status"`
	Notes               *string          `json:"notes"`
	Terms               *string          `json:"terms"`
	LedgerTransactionID *int64           `json:"ledger_transaction_id"`
	CreatedByUserID     *int64           `json:"created_by_user_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	ResourceVersion     int64            `json:"resource_version"`
	DeletedAt           pgtype.Timestamp `json:"deleted_at"`
}

type InvoiceLineItem struct {
	ID              int64            `json:"id"`
	InvoiceID       int64            `json:"invoice_id"`
	ItemID          *int64           `json:"item_id"`
	LedgerAccountID *int32           `json:"ledger_account_id"`
	LineNumber      int32            `json:"line_number"`
	Description     string           `json:"description"`
	Quantity        pgtype.Numeric   `json:"quantity"`
	UnitPrice       pgtype.Numeric   `json:"unit_price"`
	LineSubtotal    pgtype.Numeric   `json:"line_subtotal"`
	IsTaxable       bool             `json:"is_taxable"`
	TaxRateID       *int64           `json:"tax_rate_id"`
	TaxRate         pgtype.Numeric   `json:"tax_rate"`
	TaxAmount       pgtype.Numeric   `json:"tax_amount"`
	LineTotal       pgtype.Numeric   `json:"line_total"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	DeletedAt       pgtype.Timestamp `json:"deleted_at"`
}

type Item struct {
	ID                     int64            `json:"id"`
	BusinessID             int64            `json:"business_id"`
	ItemCode               string           `json:"item_code"`
	ItemType               string           `json:"item_type"`
	Name                   string           `json:"name"`
	Description            *string          `json:"description"`
	UnitOfMeasure          *string          `json:"unit_of_measure"`
	CostPrice              pgtype.Numeric   `json:"cost_price"`
	RetailPrice            pgtype.Numeric   `json:"retail_price"`
	IsTaxable              bool             `json:"is_taxable"`
	DefaultTaxRateID       *int64           `json:"default_tax_rate_id"`
	DefaultLedgerAccountID *int32           `json:"default_ledger_account_id"`
	IsActive               bool             `json:"is_active"`
	CreatedByUserID        *int64           `json:"created_by_user_id"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	ResourceVersion        int64            `json:"resource_version"`
	DeletedAt              pgtype.Timestamp `json:"deleted_at"`
}

type LedgerAccount struct {
	ID                        int32            `json:"id"`
	BusinessID                int64            `json:"business_id"`
	AccountTypeID             int32            `json:"account_type_id"`
	Code                      string           `json:"code"`
	Name                      string           `json:"name"`
	Description               *string          `json:"description"`
	ParentAccountID           *int32           `json:"parent_account_id"`
	IsSystem                  bool             `json:"is_system"`
	IsReconcilable            bool             `json:"is_reconcilable"`
	IsContainer               bool             `json:"is_container"`
	DisplaySequence           int32            `json:"display_sequence"`
	CashFlowCategoryID        *int32           `json:"cash_flow_category_id"`
	BalanceSheetCategoryID    *int32           `json:"balance_sheet_category_id"`
	IncomeStatementCategoryID *int32           `json:"income_statement_category_id"`
	IsActive                  bool             `json:"is_active"`
	CreatedByUserID           *int64           `json:"created_by_user_id"`
	CreatedAt                 pgtype.Timestamp `json:"created_at"`
	UpdatedAt                 pgtype.Timestamp `json:"updated_at"`
	ResourceVersion           int64            `json:"resource_version"`
}

type LedgerAccountType struct {
	ID            int32            `json:"id"`
	Name          string           `json:"name"`
	Description   *string          `json:"description"`
	NormalBalance string           `json:"normal_balance"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type LedgerEntry struct {
	ID                  int64            `json:"id"`
	BusinessID          int64            `json:"business_id"`
	LedgerTransactionID int64            `json:"ledger_transaction_id"`
	AccountID           int32            `json:"account_id"`
	DebitAmount         pgtype.Numeric   `json:"debit_amount"`
	CreditAmount        pgtype.Numeric   `json:"credit_amount"`
	Description         *string          `json:"description"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	DeletedAt           pgtype.Timestamp `json:"deleted_at"`
}

type LedgerTransaction struct {
	ID                          int64            `json:"id"`
	BusinessID                  int64            `json:"business_id"`
	TransactionDate             pgtype.Date      `json:"transaction_date"`
	Description                 *string          `json:"description"`
	ReferenceNumber             *string          `json:"reference_number"`
	ReversesLedgerTransactionID *int64           `json:"reverses_ledger_transaction_id"`
	CreatedByUserID             *int64           `json:"created_by_user_id"`
	CreatedAt                   pgtype.Timestamp `json:"created_at"`
	UpdatedAt                   pgtype.Timestamp `json:"updated_at"`
	DeletedAt                   pgtype.Timestamp `json:"deleted_at"`
}

type Payment struct {
	ID                  int64            `json:"id"`
	BusinessID          int64            `json:"business_id"`
	ContactID           int64            `json:"contact_id"`
	PaymentType         string           `json:"payment_type"`
	PaymentNumber       string           `json:"payment_number"`
	PaymentDate         pgtype.Date      `json:"payment_date"`
	Amount              pgtype.Numeric   `json:"amount"`
	PaymentMethod       string           `json:"payment_method"`
	ReferenceNumber     *string          `json:"reference_number"`
	Notes               *string          `json:"notes"`
	LedgerAccountID     *int32           `json:"ledger_account_id"`
	LedgerTransactionID *int64           `json:"ledger_transaction_id"`
	CreatedByUserID     *int64           `json:"created_by_user_id"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
	UpdatedAt           pgtype.Timestamp `json:"updated_at"`
	DeletedAt           pgtype.Timestamp `json:"deleted_at"`
}

type PaymentApplication struct {
	ID            int64            `json:"id"`
	PaymentID     int64            `json:"payment_id"`
	InvoiceID     int64            `json:"invoice_id"`
	AppliedAmount pgtype.Numeric   `json:"applied_amount"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type PeriodClose struct {
	ID                        int64            `json:"id"`
	BusinessID                int64            `json:"business_id"`
	PeriodStart               pgtype.Date      `json:"period_start"`
	PeriodEnd                 pgtype.Date      `json:"period_end"`
	IncomeSummaryAccountID    int32            `json:"income_summary_account_id"`
	RetainedEarningsAccountID int32            `json:"retained_earnings_account_id"`
	ClosedAt                  pgtype.Timestamp `json:"closed_at"`
	ReversedAt                pgtype.Timestamp `json:"reversed_at"`
	CreatedByUserID           *int64           `json:"created_by_user_id"`
}

type PeriodCloseEntry struct {
	ID                  int64 `json:"id"`
	PeriodCloseID       int64 `json:"period_close_id"`
	LedgerTransactionID int64 `json:"ledger_transaction_id"`
	SourceAccountID     int32 `json:"source_account_id"`
}

type TaxRate struct {
	ID                    int64            `json:"id"`
	BusinessID            int64            `json:"business_id"`
	Name                  string           `json:"name"`
	Rate                  pgtype.Numeric   `json:"rate"`
	TaxLiabilityAccountID int32            `json:"tax_liability_account_id"`
	IsActive              bool             `json:"is_active"`
	CreatedByUserID       *int64           `json:"created_by_user_id"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	UpdatedAt             pgtype.Timestamp `json:"updated_at"`
	ResourceVersion       int64            `json:"resource_version"`
}

type UserSession struct {
	ID                  int64            `json:"id"`
	UserID              int64            `json:"user_id"`
	RefreshTokenHash    string           `json:"refresh_token_hash"`
	ClientName          *string          `json:"client_name"`
	IssuedAt            pgtype.Timestamp `json:"issued_at"`
	ExpiresAt           pgtype.Timestamp `json:"expires_at"`
	LastUsedAt          pgtype.Timestamp `json:"last_used_at"`
	RevokedAt           pgtype.Timestamp `json:"revoked_at"`
	ReplacedBySessionID *int64           `json:"replaced_by_session_id"`
}

type Vendor struct {
	ID              int64            `json:"id"`
	ContactID       int64            `json:"contact_id"`
	LedgerAccountID *int32           `json:"ledger_account_id"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
}

type WebauthnCredential struct {
	ID              int64            `json:"id"`
	UserID          int64            `json:"user_id"`
	CredentialID    []byte           `json:"credential_id"`
	PublicKey       []byte           `json:"public_key"`
	AttestationType *string          `json:"attestation_type"`
	Transports      *string          `json:"transports"`
	Aaguid          []byte           `json:"aaguid"`
	SignCount       int64            `json:"sign_count"`
	BackupEligible  bool             `json:"backup_eligible"`
	BackupState     bool             `json:"backup_state"`
	Name            *string          `json:"name"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	LastUsedAt      pgtype.Timestamp `json:"last_used_at"`
}
