// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: party.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createContact = `-- name: CreateContact :one

INSERT INTO contact (
    business_id, contact_number, name,
    email, phone, payment_terms_days, credit_limit, created_by_user_id,
    billing_address_line1, billing_address_line2, billing_city, billing_state,
    billing_postal_code, billing_country
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
RETURNING id, business_id, contact_number, name, email, phone, billing_address_line1, billing_address_line2, billing_city, billing_state, billing_postal_code, billing_country, shipping_address_line1, shipping_address_line2, shipping_city, shipping_state, shipping_postal_code, shipping_country, payment_terms_days, credit_limit, is_active, created_by_user_id, created_at, updated_at, resource_version, deleted_at
`

type CreateContactParams struct {
	BusinessID          int64          `json:"business_id"`
	ContactNumber       string         `json:"contact_number"`
	Name                string         `json:"name"`
	Email               *string        `json:"email"`
	Phone               *string        `json:"phone"`
	PaymentTermsDays    *int32         `json:"payment_terms_days"`
	CreditLimit         pgtype.Numeric `json:"credit_limit"`
	CreatedByUserID     *int64         `json:"created_by_user_id"`
	BillingAddressLine1 *string        `json:"billing_address_line1"`
	BillingAddressLine2 *string        `json:"billing_address_line2"`
	BillingCity         *string        `json:"billing_city"`
	BillingState        *string        `json:"billing_state"`
	BillingPostalCode   *string        `json:"billing_postal_code"`
	BillingCountry      *string        `json:"billing_country"`
}

// Copyright (c) 2025 Silver Blueprints LLC
// SPDX-License-Identifier: MIT
func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.BusinessID,
		arg.ContactNumber,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PaymentTermsDays,
		arg.CreditLimit,
		arg.CreatedByUserID,
		arg.BillingAddressLine1,
		arg.BillingAddressLine2,
		arg.BillingCity,
		arg.BillingState,
		arg.BillingPostalCode,
		arg.BillingCountry,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ContactNumber,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.BillingAddressLine1,
		&i.BillingAddressLine2,
		&i.BillingCity,
		&i.BillingState,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.ShippingAddressLine1,
		&i.ShippingAddressLine2,
		&i.ShippingCity,
		&i.ShippingState,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
		&i.PaymentTermsDays,
		&i.CreditLimit,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customer (contact_id, ledger_account_id) VALUES ($1, $2)
RETURNING id, contact_id, ledger_account_id, created_at, updated_at
`

type CreateCustomerParams struct {
	ContactID       int64  `json:"contact_id"`
	LedgerAccountID *int32 `json:"ledger_account_id"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.ContactID, arg.LedgerAccountID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.LedgerAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO item (
    business_id, item_code, item_type, name, description, unit_of_measure, cost_price,
    retail_price, is_taxable, default_tax_rate_id, default_ledger_account_id, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, business_id, item_code, item_type, name, description, unit_of_measure, cost_price, retail_price, is_taxable, default_tax_rate_id, default_ledger_account_id, is_active, created_by_user_id, created_at, updated_at, resource_version, deleted_at
`

type CreateItemParams struct {
	BusinessID             int64          `json:"business_id"`
	ItemCode               string         `json:"item_code"`
	ItemType               string         `json:"item_type"`
	Name                   string         `json:"name"`
	Description            *string        `json:"description"`
	UnitOfMeasure          *string        `json:"unit_of_measure"`
	CostPrice              pgtype.Numeric `json:"cost_price"`
	RetailPrice            pgtype.Numeric `json:"retail_price"`
	IsTaxable              bool           `json:"is_taxable"`
	DefaultTaxRateID       *int64         `json:"default_tax_rate_id"`
	DefaultLedgerAccountID *int32         `json:"default_ledger_account_id"`
	CreatedByUserID        *int64         `json:"created_by_user_id"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.BusinessID,
		arg.ItemCode,
		arg.ItemType,
		arg.Name,
		arg.Description,
		arg.UnitOfMeasure,
		arg.CostPrice,
		arg.RetailPrice,
		arg.IsTaxable,
		arg.DefaultTaxRateID,
		arg.DefaultLedgerAccountID,
		arg.CreatedByUserID,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ItemCode,
		&i.ItemType,
		&i.Name,
		&i.Description,
		&i.UnitOfMeasure,
		&i.CostPrice,
		&i.RetailPrice,
		&i.IsTaxable,
		&i.DefaultTaxRateID,
		&i.DefaultLedgerAccountID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const createTaxRate = `-- name: CreateTaxRate :one
INSERT INTO tax_rate (
    business_id, name, rate, tax_liability_account_id, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, business_id, name, rate, tax_liability_account_id, is_active, created_by_user_id, created_at, updated_at, resource_version
`

type CreateTaxRateParams struct {
	BusinessID            int64          `json:"business_id"`
	Name                  string         `json:"name"`
	Rate                  pgtype.Numeric `json:"rate"`
	TaxLiabilityAccountID int32          `json:"tax_liability_account_id"`
	CreatedByUserID       *int64         `json:"created_by_user_id"`
}

func (q *Queries) CreateTaxRate(ctx context.Context, arg CreateTaxRateParams) (TaxRate, error) {
	row := q.db.QueryRow(ctx, createTaxRate,
		arg.BusinessID,
		arg.Name,
		arg.Rate,
		arg.TaxLiabilityAccountID,
		arg.CreatedByUserID,
	)
	var i TaxRate
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Rate,
		&i.TaxLiabilityAccountID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
	)
	return i, err
}

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendor (contact_id, ledger_account_id) VALUES ($1, $2)
RETURNING id, contact_id, ledger_account_id, created_at, updated_at
`

type CreateVendorParams struct {
	ContactID       int64  `json:"contact_id"`
	LedgerAccountID *int32 `json:"ledger_account_id"`
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, createVendor, arg.ContactID, arg.LedgerAccountID)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.LedgerAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateContact = `-- name: DeactivateContact :one
UPDATE contact SET is_active = FALSE, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
    AND ($2::bigint IS NULL OR resource_version = $2)
RETURNING id, business_id, contact_number, name, email, phone, billing_address_line1, billing_address_line2, billing_city, billing_state, billing_postal_code, billing_country, shipping_address_line1, shipping_address_line2, shipping_city, shipping_state, shipping_postal_code, shipping_country, payment_terms_days, credit_limit, is_active, created_by_user_id, created_at, updated_at, resource_version, deleted_at
`

type DeactivateContactParams struct {
	ID              int64  `json:"id"`
	ResourceVersion *int64 `json:"resource_version"`
}

func (q *Queries) DeactivateContact(ctx context.Context, arg DeactivateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, deactivateContact, arg.ID, arg.ResourceVersion)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ContactNumber,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.BillingAddressLine1,
		&i.BillingAddressLine2,
		&i.BillingCity,
		&i.BillingState,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.ShippingAddressLine1,
		&i.ShippingAddressLine2,
		&i.ShippingCity,
		&i.ShippingState,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
		&i.PaymentTermsDays,
		&i.CreditLimit,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateItem = `-- name: DeactivateItem :one
UPDATE item SET is_active = FALSE, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
    AND ($2::bigint IS NULL OR resource_version = $2)
RETURNING id, business_id, item_code, item_type, name, description, unit_of_measure, cost_price, retail_price, is_taxable, default_tax_rate_id, default_ledger_account_id, is_active, created_by_user_id, created_at, updated_at, resource_version, deleted_at
`

type DeactivateItemParams struct {
	ID              int64  `json:"id"`
	ResourceVersion *int64 `json:"resource_version"`
}

func (q *Queries) DeactivateItem(ctx context.Context, arg DeactivateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, deactivateItem, arg.ID, arg.ResourceVersion)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ItemCode,
		&i.ItemType,
		&i.Name,
		&i.Description,
		&i.UnitOfMeasure,
		&i.CostPrice,
		&i.RetailPrice,
		&i.IsTaxable,
		&i.DefaultTaxRateID,
		&i.DefaultLedgerAccountID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateTaxRate = `-- name: DeactivateTaxRate :one
UPDATE tax_rate SET is_active = FALSE, updated_at = NOW()
WHERE id = $1
    AND ($2::bigint IS NULL OR resource_version = $2)
RETURNING id, business_id, name, rate, tax_liability_account_id, is_active, created_by_user_id, created_at, updated_at, resource_version
`

type DeactivateTaxRateParams struct {
	ID              int64  `json:"id"`
	ResourceVersion *int64 `json:"resource_version"`
}

func (q *Queries) DeactivateTaxRate(ctx context.Context, arg DeactivateTaxRateParams) (TaxRate, error) {
	row := q.db.QueryRow(ctx, deactivateTaxRate, arg.ID, arg.ResourceVersion)
	var i TaxRate
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Rate,
		&i.TaxLiabilityAccountID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
	)
	return i, err
}

const getContact = `-- name: GetContact :one
SELECT id, business_id, contact_number, name, email, phone, billing_address_line1, billing_address_line2, billing_city, billing_state, billing_postal_code, billing_country, shipping_address_line1, shipping_address_line2, shipping_city, shipping_state, shipping_postal_code, shipping_country, payment_terms_days, credit_limit, is_active, created_by_user_id, created_at, updated_at, resource_version, deleted_at FROM contact WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetContact(ctx context.Context, id int64) (Contact, error) {
	row := q.db.QueryRow(ctx, getContact, id)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ContactNumber,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.BillingAddressLine1,
		&i.BillingAddressLine2,
		&i.BillingCity,
		&i.BillingState,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.ShippingAddressLine1,
		&i.ShippingAddressLine2,
		&i.ShippingCity,
		&i.ShippingState,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
		&i.PaymentTermsDays,
		&i.CreditLimit,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const getCustomerByContactID = `-- name: GetCustomerByContactID :one
SELECT id, contact_id, ledger_account_id, created_at, updated_at FROM customer WHERE contact_id = $1
`

func (q *Queries) GetCustomerByContactID(ctx context.Context, contactID int64) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByContactID, contactID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.LedgerAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, business_id, item_code, item_type, name, description, unit_of_measure, cost_price, retail_price, is_taxable, default_tax_rate_id, default_ledger_account_id, is_active, created_by_user_id, created_at, updated_at, resource_version, deleted_at FROM item WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetItem(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ItemCode,
		&i.ItemType,
		&i.Name,
		&i.Description,
		&i.UnitOfMeasure,
		&i.CostPrice,
		&i.RetailPrice,
		&i.IsTaxable,
		&i.DefaultTaxRateID,
		&i.DefaultLedgerAccountID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const getTaxRate = `-- name: GetTaxRate :one
SELECT id, business_id, name, rate, tax_liability_account_id, is_active, created_by_user_id, created_at, updated_at, resource_version FROM tax_rate WHERE id = $1
`

func (q *Queries) GetTaxRate(ctx context.Context, id int64) (TaxRate, error) {
	row := q.db.QueryRow(ctx, getTaxRate, id)
	var i TaxRate
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Rate,
		&i.TaxLiabilityAccountID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
	)
	return i, err
}

const getVendorByContactID = `-- name: GetVendorByContactID :one
SELECT id, contact_id, ledger_account_id, created_at, updated_at FROM vendor WHERE contact_id = $1
`

func (q *Queries) GetVendorByContactID(ctx context.Context, contactID int64) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByContactID, contactID)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.ContactID,
		&i.LedgerAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContacts = `-- name: ListContacts :many
SELECT id, business_id, contact_number, name, email, phone, billing_address_line1, billing_address_line2, billing_city, billing_state, billing_postal_code, billing_country, shipping_address_line1, shipping_address_line2, shipping_city, shipping_state, shipping_postal_code, shipping_country, payment_terms_days, credit_limit, is_active, created_by_user_id, created_at, updated_at, resource_version, deleted_at FROM contact
WHERE business_id = $1 AND deleted_at IS NULL
    AND (is_active OR $2::bool)
ORDER BY name
`

type ListContactsParams struct {
	BusinessID      int64 `json:"business_id"`
	IncludeInactive bool  `json:"include_inactive"`
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]Contact, error) {
	rows, err := q.db.Query(ctx, listContacts, arg.BusinessID, arg.IncludeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Contact
	for rows.Next() {
		var i Contact
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ContactNumber,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.BillingAddressLine1,
			&i.BillingAddressLine2,
			&i.BillingCity,
			&i.BillingState,
			&i.BillingPostalCode,
			&i.BillingCountry,
			&i.ShippingAddressLine1,
			&i.ShippingAddressLine2,
			&i.ShippingCity,
			&i.ShippingState,
			&i.ShippingPostalCode,
			&i.ShippingCountry,
			&i.PaymentTermsDays,
			&i.CreditLimit,
			&i.IsActive,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceVersion,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomersByContactIDs = `-- name: ListCustomersByContactIDs :many
SELECT id, contact_id, ledger_account_id, created_at, updated_at FROM customer WHERE contact_id = ANY($1::bigint[])
`

// Batch form for contact list handlers.
func (q *Queries) ListCustomersByContactIDs(ctx context.Context, contactIds []int64) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomersByContactIDs, contactIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.LedgerAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, business_id, item_code, item_type, name, description, unit_of_measure, cost_price, retail_price, is_taxable, default_tax_rate_id, default_ledger_account_id, is_active, created_by_user_id, created_at, updated_at, resource_version, deleted_at FROM item
WHERE business_id = $1 AND deleted_at IS NULL
    AND (is_active OR $2::bool)
ORDER BY item_code
`

type ListItemsParams struct {
	BusinessID      int64 `json:"business_id"`
	IncludeInactive bool  `json:"include_inactive"`
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]Item, error) {
	rows, err := q.db.Query(ctx, listItems, arg.BusinessID, arg.IncludeInactive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.ItemCode,
			&i.ItemType,
			&i.Name,
			&i.Description,
			&i.UnitOfMeasure,
			&i.CostPrice,
			&i.RetailPrice,
			&i.IsTaxable,
			&i.DefaultTaxRateID,
			&i.DefaultLedgerAccountID,
			&i.IsActive,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceVersion,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaxRates = `-- name: ListTaxRates :many
SELECT id, business_id, name, rate, tax_liability_account_id, is_active, created_by_user_id, created_at, updated_at, resource_version FROM tax_rate WHERE business_id = $1 ORDER BY name
`

func (q *Queries) ListTaxRates(ctx context.Context, businessID int64) ([]TaxRate, error) {
	rows, err := q.db.Query(ctx, listTaxRates, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxRate
	for rows.Next() {
		var i TaxRate
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.Name,
			&i.Rate,
			&i.TaxLiabilityAccountID,
			&i.IsActive,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVendorsByContactIDs = `-- name: ListVendorsByContactIDs :many
SELECT id, contact_id, ledger_account_id, created_at, updated_at FROM vendor WHERE contact_id = ANY($1::bigint[])
`

func (q *Queries) ListVendorsByContactIDs(ctx context.Context, contactIds []int64) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, listVendorsByContactIDs, contactIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vendor
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.ContactID,
			&i.LedgerAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :one
UPDATE contact SET
    name = COALESCE($1, name),
    email = COALESCE($2, email),
    phone = COALESCE($3, phone),
    payment_terms_days = COALESCE($4, payment_terms_days),
    credit_limit = COALESCE($5, credit_limit),
    billing_address_line1 = COALESCE($6, billing_address_line1),
    billing_address_line2 = COALESCE($7, billing_address_line2),
    billing_city = COALESCE($8, billing_city),
    billing_state = COALESCE($9, billing_state),
    billing_postal_code = COALESCE($10, billing_postal_code),
    billing_country = COALESCE($11, billing_country),
    updated_at = NOW()
WHERE id = $12 AND deleted_at IS NULL
    AND ($13::bigint IS NULL OR resource_version = $13)
RETURNING id, business_id, contact_number, name, email, phone, billing_address_line1, billing_address_line2, billing_city, billing_state, billing_postal_code, billing_country, shipping_address_line1, shipping_address_line2, shipping_city, shipping_state, shipping_postal_code, shipping_country, payment_terms_days, credit_limit, is_active, created_by_user_id, created_at, updated_at, resource_version, deleted_at
`

type UpdateContactParams struct {
	Name                *string        `json:"name"`
	Email               *string        `json:"email"`
	Phone               *string        `json:"phone"`
	PaymentTermsDays    *int32         `json:"payment_terms_days"`
	CreditLimit         pgtype.Numeric `json:"credit_limit"`
	BillingAddressLine1 *string        `json:"billing_address_line1"`
	BillingAddressLine2 *string        `json:"billing_address_line2"`
	BillingCity         *string        `json:"billing_city"`
	BillingState        *string        `json:"billing_state"`
	BillingPostalCode   *string        `json:"billing_postal_code"`
	BillingCountry      *string        `json:"billing_country"`
	ID                  int64          `json:"id"`
	ResourceVersion     *int64         `json:"resource_version"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (Contact, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PaymentTermsDays,
		arg.CreditLimit,
		arg.BillingAddressLine1,
		arg.BillingAddressLine2,
		arg.BillingCity,
		arg.BillingState,
		arg.BillingPostalCode,
		arg.BillingCountry,
		arg.ID,
		arg.ResourceVersion,
	)
	var i Contact
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ContactNumber,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.BillingAddressLine1,
		&i.BillingAddressLine2,
		&i.BillingCity,
		&i.BillingState,
		&i.BillingPostalCode,
		&i.BillingCountry,
		&i.ShippingAddressLine1,
		&i.ShippingAddressLine2,
		&i.ShippingCity,
		&i.ShippingState,
		&i.ShippingPostalCode,
		&i.ShippingCountry,
		&i.PaymentTermsDays,
		&i.CreditLimit,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const updateItem = `-- name: UpdateItem :one
UPDATE item SET
    item_type = COALESCE($1, item_type),
    name = COALESCE($2, name),
    description = COALESCE($3, description),
    retail_price = COALESCE($4, retail_price),
    cost_price = COALESCE($5, cost_price),
    is_taxable = COALESCE($6, is_taxable),
    default_tax_rate_id = COALESCE($7, default_tax_rate_id),
    default_ledger_account_id = COALESCE($8, default_ledger_account_id),
    updated_at = NOW()
WHERE id = $9 AND deleted_at IS NULL
    AND ($10::bigint IS NULL OR resource_version = $10)
RETURNING id, business_id, item_code, item_type, name, description, unit_of_measure, cost_price, retail_price, is_taxable, default_tax_rate_id, default_ledger_account_id, is_active, created_by_user_id, created_at, updated_at, resource_version, deleted_at
`

type UpdateItemParams struct {
	ItemType               *string        `json:"item_type"`
	Name                   *string        `json:"name"`
	Description            *string        `json:"description"`
	RetailPrice            pgtype.Numeric `json:"retail_price"`
	CostPrice              pgtype.Numeric `json:"cost_price"`
	IsTaxable              *bool          `json:"is_taxable"`
	DefaultTaxRateID       *int64         `json:"default_tax_rate_id"`
	DefaultLedgerAccountID *int32         `json:"default_ledger_account_id"`
	ID                     int64          `json:"id"`
	ResourceVersion        *int64         `json:"resource_version"`
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.ItemType,
		arg.Name,
		arg.Description,
		arg.RetailPrice,
		arg.CostPrice,
		arg.IsTaxable,
		arg.DefaultTaxRateID,
		arg.DefaultLedgerAccountID,
		arg.ID,
		arg.ResourceVersion,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.ItemCode,
		&i.ItemType,
		&i.Name,
		&i.Description,
		&i.UnitOfMeasure,
		&i.CostPrice,
		&i.RetailPrice,
		&i.IsTaxable,
		&i.DefaultTaxRateID,
		&i.DefaultLedgerAccountID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
		&i.DeletedAt,
	)
	return i, err
}

const updateTaxRate = `-- name: UpdateTaxRate :one
UPDATE tax_rate SET
    name = COALESCE($1, name),
    rate = COALESCE($2, rate),
    updated_at = NOW()
WHERE id = $3
    AND ($4::bigint IS NULL OR resource_version = $4)
RETURNING id, business_id, name, rate, tax_liability_account_id, is_active, created_by_user_id, created_at, updated_at, resource_version
`

type UpdateTaxRateParams struct {
	Name            *string        `json:"name"`
	Rate            pgtype.Numeric `json:"rate"`
	ID              int64          `json:"id"`
	ResourceVersion *int64         `json:"resource_version"`
}

func (q *Queries) UpdateTaxRate(ctx context.Context, arg UpdateTaxRateParams) (TaxRate, error) {
	row := q.db.QueryRow(ctx, updateTaxRate,
		arg.Name,
		arg.Rate,
		arg.ID,
		arg.ResourceVersion,
	)
	var i TaxRate
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.Name,
		&i.Rate,
		&i.TaxLiabilityAccountID,
		&i.IsActive,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResourceVersion,
	)
	return i, err
}
