// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: period_close.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPeriodClose = `-- name: CreatePeriodClose :one

INSERT INTO period_close (
    business_id, period_start, period_end, income_summary_account_id,
    retained_earnings_account_id, created_by_user_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, business_id, period_start, period_end, income_summary_account_id, retained_earnings_account_id, closed_at, reversed_at, created_by_user_id
`

type CreatePeriodCloseParams struct {
	BusinessID                int64       `json:"business_id"`
	PeriodStart               pgtype.Date `json:"period_start"`
	PeriodEnd                 pgtype.Date `json:"period_end"`
	IncomeSummaryAccountID    int32       `json:"income_summary_account_id"`
	RetainedEarningsAccountID int32       `json:"retained_earnings_account_id"`
	CreatedByUserID           *int64      `json:"created_by_user_id"`
}

// Copyright (c) 2025 Silver Blueprints LLC
// SPDX-License-Identifier: MIT
func (q *Queries) CreatePeriodClose(ctx context.Context, arg CreatePeriodCloseParams) (PeriodClose, error) {
	row := q.db.QueryRow(ctx, createPeriodClose,
		arg.BusinessID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.IncomeSummaryAccountID,
		arg.RetainedEarningsAccountID,
		arg.CreatedByUserID,
	)
	var i PeriodClose
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IncomeSummaryAccountID,
		&i.RetainedEarningsAccountID,
		&i.ClosedAt,
		&i.ReversedAt,
		&i.CreatedByUserID,
	)
	return i, err
}

const createPeriodCloseEntry = `-- name: CreatePeriodCloseEntry :one
INSERT INTO period_close_entry (period_close_id, ledger_transaction_id, source_account_id)
VALUES ($1, $2, $3)
RETURNING id, period_close_id, ledger_transaction_id, source_account_id
`

type CreatePeriodCloseEntryParams struct {
	PeriodCloseID       int64 `json:"period_close_id"`
	LedgerTransactionID int64 `json:"ledger_transaction_id"`
	SourceAccountID     int32 `json:"source_account_id"`
}

func (q *Queries) CreatePeriodCloseEntry(ctx context.Context, arg CreatePeriodCloseEntryParams) (PeriodCloseEntry, error) {
	row := q.db.QueryRow(ctx, createPeriodCloseEntry, arg.PeriodCloseID, arg.LedgerTransactionID, arg.SourceAccountID)
	var i PeriodCloseEntry
	err := row.Scan(
		&i.ID,
		&i.PeriodCloseID,
		&i.LedgerTransactionID,
		&i.SourceAccountID,
	)
	return i, err
}

const getPeriodClose = `-- name: GetPeriodClose :one
SELECT id, business_id, period_start, period_end, income_summary_account_id, retained_earnings_account_id, closed_at, reversed_at, created_by_user_id FROM period_close WHERE id = $1
`

func (q *Queries) GetPeriodClose(ctx context.Context, id int64) (PeriodClose, error) {
	row := q.db.QueryRow(ctx, getPeriodClose, id)
	var i PeriodClose
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IncomeSummaryAccountID,
		&i.RetainedEarningsAccountID,
		&i.ClosedAt,
		&i.ReversedAt,
		&i.CreatedByUserID,
	)
	return i, err
}

const listPeriodCloseEntries = `-- name: ListPeriodCloseEntries :many
SELECT id, period_close_id, ledger_transaction_id, source_account_id FROM period_close_entry WHERE period_close_id = $1 ORDER BY id
`

func (q *Queries) ListPeriodCloseEntries(ctx context.Context, periodCloseID int64) ([]PeriodCloseEntry, error) {
	rows, err := q.db.Query(ctx, listPeriodCloseEntries, periodCloseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodCloseEntry
	for rows.Next() {
		var i PeriodCloseEntry
		if err := rows.Scan(
			&i.ID,
			&i.PeriodCloseID,
			&i.LedgerTransactionID,
			&i.SourceAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriodCloseEntriesByCloseIDs = `-- name: ListPeriodCloseEntriesByCloseIDs :many
SELECT id, period_close_id, ledger_transaction_id, source_account_id FROM period_close_entry
WHERE period_close_id = ANY($1::bigint[])
ORDER BY period_close_id, id
`

// Batch form for list handlers.
func (q *Queries) ListPeriodCloseEntriesByCloseIDs(ctx context.Context, periodCloseIds []int64) ([]PeriodCloseEntry, error) {
	rows, err := q.db.Query(ctx, listPeriodCloseEntriesByCloseIDs, periodCloseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodCloseEntry
	for rows.Next() {
		var i PeriodCloseEntry
		if err := rows.Scan(
			&i.ID,
			&i.PeriodCloseID,
			&i.LedgerTransactionID,
			&i.SourceAccountID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriodCloses = `-- name: ListPeriodCloses :many
SELECT id, business_id, period_start, period_end, income_summary_account_id, retained_earnings_account_id, closed_at, reversed_at, created_by_user_id FROM period_close WHERE business_id = $1 ORDER BY period_end DESC
`

func (q *Queries) ListPeriodCloses(ctx context.Context, businessID int64) ([]PeriodClose, error) {
	rows, err := q.db.Query(ctx, listPeriodCloses, businessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeriodClose
	for rows.Next() {
		var i PeriodClose
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.IncomeSummaryAccountID,
			&i.RetainedEarningsAccountID,
			&i.ClosedAt,
			&i.ReversedAt,
			&i.CreatedByUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reversePeriodClose = `-- name: ReversePeriodClose :one
UPDATE period_close SET reversed_at = NOW()
WHERE id = $1 AND reversed_at IS NULL
RETURNING id, business_id, period_start, period_end, income_summary_account_id, retained_earnings_account_id, closed_at, reversed_at, created_by_user_id
`

func (q *Queries) ReversePeriodClose(ctx context.Context, id int64) (PeriodClose, error) {
	row := q.db.QueryRow(ctx, reversePeriodClose, id)
	var i PeriodClose
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IncomeSummaryAccountID,
		&i.RetainedEarningsAccountID,
		&i.ClosedAt,
		&i.ReversedAt,
		&i.CreatedByUserID,
	)
	return i, err
}
