// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reference.sql

package sqlcgen

import (
	"context"
)

const listBalanceSheetCategories = `-- name: ListBalanceSheetCategories :many
SELECT id, name, display_sequence FROM balance_sheet_category ORDER BY display_sequence
`

func (q *Queries) ListBalanceSheetCategories(ctx context.Context) ([]BalanceSheetCategory, error) {
	rows, err := q.db.Query(ctx, listBalanceSheetCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BalanceSheetCategory
	for rows.Next() {
		var i BalanceSheetCategory
		if err := rows.Scan(&i.ID, &i.Name, &i.DisplaySequence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashFlowCategories = `-- name: ListCashFlowCategories :many
SELECT id, name, display_sequence FROM cash_flow_category ORDER BY display_sequence
`

func (q *Queries) ListCashFlowCategories(ctx context.Context) ([]CashFlowCategory, error) {
	rows, err := q.db.Query(ctx, listCashFlowCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CashFlowCategory
	for rows.Next() {
		var i CashFlowCategory
		if err := rows.Scan(&i.ID, &i.Name, &i.DisplaySequence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomeStatementCategories = `-- name: ListIncomeStatementCategories :many
SELECT id, name, display_sequence FROM income_statement_category ORDER BY display_sequence
`

func (q *Queries) ListIncomeStatementCategories(ctx context.Context) ([]IncomeStatementCategory, error) {
	rows, err := q.db.Query(ctx, listIncomeStatementCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IncomeStatementCategory
	for rows.Next() {
		var i IncomeStatementCategory
		if err := rows.Scan(&i.ID, &i.Name, &i.DisplaySequence); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerAccountTypes = `-- name: ListLedgerAccountTypes :many

SELECT id, name, description, normal_balance, created_at, updated_at FROM ledger_account_type ORDER BY id
`

// Copyright (c) 2025 Silver Blueprints LLC
// SPDX-License-Identifier: MIT
func (q *Queries) ListLedgerAccountTypes(ctx context.Context) ([]LedgerAccountType, error) {
	rows, err := q.db.Query(ctx, listLedgerAccountTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerAccountType
	for rows.Next() {
		var i LedgerAccountType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.NormalBalance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
