// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reporting.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountBalancesAsOf = `-- name: AccountBalancesAsOf :many

SELECT
    la.id AS account_id,
    la.code,
    la.name,
    la.account_type_id,
    la.parent_account_id,
    la.is_container,
    la.balance_sheet_category_id,
    la.income_statement_category_id,
    lat.normal_balance,
    COALESCE(SUM(CASE WHEN lt.transaction_date BETWEEN $1 AND $2 THEN le.debit_amount ELSE 0 END), 0)::numeric AS total_debit,
    COALESCE(SUM(CASE WHEN lt.transaction_date BETWEEN $1 AND $2 THEN le.credit_amount ELSE 0 END), 0)::numeric AS total_credit
FROM ledger_account la
JOIN ledger_account_type lat ON lat.id = la.account_type_id
LEFT JOIN ledger_entry le ON le.account_id = la.id AND le.deleted_at IS NULL
LEFT JOIN ledger_transaction lt ON lt.id = le.ledger_transaction_id AND lt.deleted_at IS NULL
WHERE la.business_id = $3
GROUP BY la.id, la.code, la.name, la.account_type_id, la.parent_account_id, la.is_container, la.balance_sheet_category_id, la.income_statement_category_id, lat.normal_balance
ORDER BY la.code
`

type AccountBalancesAsOfParams struct {
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
	BusinessID  int64       `json:"business_id"`
}

type AccountBalancesAsOfRow struct {
	AccountID                 int32          `json:"account_id"`
	Code                      string         `json:"code"`
	Name                      string         `json:"name"`
	AccountTypeID             int32          `json:"account_type_id"`
	ParentAccountID           *int32         `json:"parent_account_id"`
	IsContainer               bool           `json:"is_container"`
	BalanceSheetCategoryID    *int32         `json:"balance_sheet_category_id"`
	IncomeStatementCategoryID *int32         `json:"income_statement_category_id"`
	NormalBalance             string         `json:"normal_balance"`
	TotalDebit                pgtype.Numeric `json:"total_debit"`
	TotalCredit               pgtype.Numeric `json:"total_credit"`
}

// Copyright (c) 2025 Silver Blueprints LLC
// SPDX-License-Identifier: MIT
// One row per ledger_account, with total debit/credit activity from
// ledger_entry within [period_start, period_end]. Used, with different
// date ranges, for trial balance and balance sheet ("as of": period_start
// = business inception) and income statement (an arbitrary range).
//
// Both joins are LEFT and date-unconditional (so every account survives
// even with zero activity); the date range is applied inside the SUM's
// CASE instead of in a JOIN...ON clause. Filtering by date in a LEFT JOIN's
// ON clause does NOT exclude out-of-range ledger_entry rows from the sum -
// it only nulls out the unmatched ledger_transaction columns, while
// ledger_entry's own debit/credit columns (already bound by the prior
// join) stay non-null and still get summed.
func (q *Queries) AccountBalancesAsOf(ctx context.Context, arg AccountBalancesAsOfParams) ([]AccountBalancesAsOfRow, error) {
	rows, err := q.db.Query(ctx, accountBalancesAsOf, arg.PeriodStart, arg.PeriodEnd, arg.BusinessID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountBalancesAsOfRow
	for rows.Next() {
		var i AccountBalancesAsOfRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Code,
			&i.Name,
			&i.AccountTypeID,
			&i.ParentAccountID,
			&i.IsContainer,
			&i.BalanceSheetCategoryID,
			&i.IncomeStatementCategoryID,
			&i.NormalBalance,
			&i.TotalDebit,
			&i.TotalCredit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastPeriodClose = `-- name: GetLastPeriodClose :one
SELECT id, business_id, period_start, period_end, income_summary_account_id, retained_earnings_account_id, closed_at, reversed_at, created_by_user_id FROM period_close
WHERE business_id = $1 AND reversed_at IS NULL
ORDER BY period_end DESC
LIMIT 1
`

func (q *Queries) GetLastPeriodClose(ctx context.Context, businessID int64) (PeriodClose, error) {
	row := q.db.QueryRow(ctx, getLastPeriodClose, businessID)
	var i PeriodClose
	err := row.Scan(
		&i.ID,
		&i.BusinessID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IncomeSummaryAccountID,
		&i.RetainedEarningsAccountID,
		&i.ClosedAt,
		&i.ReversedAt,
		&i.CreatedByUserID,
	)
	return i, err
}

const listLedgerEntriesForAccount = `-- name: ListLedgerEntriesForAccount :many
SELECT
    le.id, le.business_id, le.ledger_transaction_id, le.account_id, le.debit_amount, le.credit_amount, le.description, le.created_at, le.updated_at, le.deleted_at,
    lt.transaction_date,
    lt.description AS transaction_description,
    lt.reference_number
FROM ledger_entry le
JOIN ledger_transaction lt ON lt.id = le.ledger_transaction_id AND lt.deleted_at IS NULL
WHERE le.account_id = $1
    AND le.deleted_at IS NULL
    AND lt.transaction_date BETWEEN $2 AND $3
ORDER BY lt.transaction_date, le.id
`

type ListLedgerEntriesForAccountParams struct {
	AccountID   int32       `json:"account_id"`
	PeriodStart pgtype.Date `json:"period_start"`
	PeriodEnd   pgtype.Date `json:"period_end"`
}

type ListLedgerEntriesForAccountRow struct {
	ID                     int64            `json:"id"`
	BusinessID             int64            `json:"business_id"`
	LedgerTransactionID    int64            `json:"ledger_transaction_id"`
	AccountID              int32            `json:"account_id"`
	DebitAmount            pgtype.Numeric   `json:"debit_amount"`
	CreditAmount           pgtype.Numeric   `json:"credit_amount"`
	Description            *string          `json:"description"`
	CreatedAt              pgtype.Timestamp `json:"created_at"`
	UpdatedAt              pgtype.Timestamp `json:"updated_at"`
	DeletedAt              pgtype.Timestamp `json:"deleted_at"`
	TransactionDate        pgtype.Date      `json:"transaction_date"`
	TransactionDescription *string          `json:"transaction_description"`
	ReferenceNumber        *string          `json:"reference_number"`
}

func (q *Queries) ListLedgerEntriesForAccount(ctx context.Context, arg ListLedgerEntriesForAccountParams) ([]ListLedgerEntriesForAccountRow, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesForAccount, arg.AccountID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLedgerEntriesForAccountRow
	for rows.Next() {
		var i ListLedgerEntriesForAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessID,
			&i.LedgerTransactionID,
			&i.AccountID,
			&i.DebitAmount,
			&i.CreditAmount,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.TransactionDate,
			&i.TransactionDescription,
			&i.ReferenceNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
